### ISSUE TITLE
Problems to understand the Users Inputs on Virtual Assistant Sample - Virtual Assistant Sample not work

### ISSUE THREAD

**Issue by fidelitymobileorg** [microsoft/botframework-solutions#3854] opened 2022-02-03 18:59 UTC
#### What project is affected?

Virtual Assistant

#### What language is this in?

C# and JS

#### What happens?

Virtual Assistant not understand the Users Inputs

#### What are the steps to reproduce this issue?

1) Deploy Virtual Assistant template with PowerShell at Azure
2) Run WebChat
3) Send knowledge messages on WebChat
4) Virtual Assistant reaturn de default message (because return null from knowledge)

#### What were you expecting to happen?

Virtual Assistant returns the Right Answers from Knowledge

ScreenShots:

![VATESTINTENT](https://user-images.githubusercontent.com/98978863/152410495-dfed111e-1bef-4807-a705-2d4f0a988e2c.png)

**Comment by lauren-mills** [comment] 2022-02-04 19:39
Hi @fidelitymobileorg, it appears from the screenshot that the bot is returning a ChitChat knowledge base response to your question. If you have not added custom QnA pairs, I would say this is the expected behavior, because the built-in knowledge bases in the template do not handle that query by default. You can see [here ](https://github.com/microsoft/botframework-solutions/blob/b8e8ccdf2c52b323d961be84ed55f99b624dca38/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Resources/QnA/en-us/Chitchat.qna#L6875) where the chitchat model is returning the "Great, thanks" answer.

If you have created a custom knowledge base which should be able to handle the "What day is today?" query, have you run the update cognitive models script to ensure your dispatch model is updated with your custom QnA pairs?

**Comment by fidelitymobileorg** [comment] 2022-02-04 20:49
Hi @lauren-mills ,

We hope you are well and healthy!

- Lauren, the screenshot demonstrates a failure return on the "MainDialog.cs" file event, as there are two knowledge bases, and this message "What day is today?" has a couple of replies as well as other messages like "Good morning", "Good afternoon", "Good evening" and have the same problem.

- Lauren, custom QnA pairs were added, so this is not the expected behavior as it should return the message from the QnA pairs.
 
- Yes Lauren, a custom knowledge base was created that handles the question "What day is today?" as well as other questions like "Good morning", "Good afternoon", "Good evening" and have the same bug even after run the cognitive models update script to ensure the dispatch model is updated with the custom QnA pairs.
 
- So Lauren, the flaw is that even with the QnA pairs created, trained and updated, the "QnAConfiguration" and "BeginDialogAsync" events return wrong messages, that is, they do not respond as expected, configuring a Bug that needs to be fixed in the library from BotFramework.
 
- Lauren, reinforcing, what we technically report is a bug that results in this "misunderstood" issue of user questions, which needs to be fixed in the BotFramework library (Microsoft.Bot).
 
- Lauren, what were you expecting to happen is the Virtual Assistant returns the Right Answers from Knowledge.

**Comment by lauren-mills** [comment] 2022-02-14 23:50
Thanks for your response. Can you please answer these questions to help me repro this behavior? I was not able to based on this information alone. 

- Did you create a completely new knowledge base, or add new QnA pairs to either the FAQ or ChitChat knowledge bases created in the Virtual Assistant project?
- Did you publish the knowledge base changes before running the update_cognitive_models script?
- When running the update_cognitive_models scripts *with the -RemoteToLocal flag* can you verify that the .dispatch and .qna files in your Deployment/Resources folder contain these changes? You should be able to do a ctrl-f search to verify they have been correctly downloaded from the published knowledge bases

Finally, if this is for a new project, I recommend starting with the Core Assistant Bot in Bot Framework Composer, as support for this template will end on March 31st.

**Comment by johnataylor** [comment] 2022-02-28 19:17
closing as this has been 14days, please reopen if you have further issues

**Closed as completed by johnataylor** 2022-02-28 19:17 UTC
Labels: customer-reported, customer-replied-to, Bot Services
