### ISSUE TITLE
Token exchange process starts but rise an InternalServerError exception.

### ISSUE THREAD

**Issue by GitDruid** [microsoft/botframework-solutions#3654] opened 2020-09-14 07:44 UTC
The token exchange process starts but rise an InternalServerError exception (see attachment).

[Exception on token exchange.txt](https://github.com/microsoft/botframework-solutions/files/4967634/Exception.on.token.exchange.txt)

_Originally posted by @GitDruid in https://github.com/microsoft/botframework-solutions/issues/3579#issuecomment-663121663_

**Comment by tdurnford** [comment] 2020-09-22 01:37
@Batta32 Can you take a look at this?

**Comment by Batta32** [comment] 2020-09-22 12:14
Sure @tdurnford! We will be reviewing this issue and the PR #3655. As soon as we have any update, we will back here 😊.

**Comment by VictorGrycuk** [comment] 2020-09-24 20:18
Hi @GitDruid, we were able to **reproduce** the InternalServerError exception.

So far the changes made on the PR [#3655](https://github.com/microsoft/botframework-solutions/pull/3655) seems to be right regarding the botbuilder [SDK](https://github.com/microsoft/botbuilder-dotnet/blob/bdf9ef368295f1fe150d5793520be86e76a01437/libraries/Microsoft.Bot.Builder/OAuth/IExtendedUserTokenProvider.cs#L138) and following the sample [sso-with-skills](https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/sso-with-skills), but we want to validate that it does fix the error.

As soon as we have any update, we will back to you 😊.

*InternalServerError exception*
![image](https://user-images.githubusercontent.com/39467613/94195851-eee23c00-fe89-11ea-9cc0-ba27a7751360.png)

**Comment by Batta32** [comment] 2020-09-25 21:25
@tdurnford & @GitDruid - after reviewing the changes of PR #3655, we confirmed that the changes are **correct** and follows the signature of the `ExchangeTokenAsync` of [IExtendedUserTokenProvider](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/OAuth/IExtendedUserTokenProvider.cs#L138) for botbuilder-dotnet and the parameters had to be inverted. Also, in botbuilder-js the signature is the [same](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/extendedUserTokenProvider.ts#L85) and the sample [sso-with-skills](https://github.com/microsoft/BotBuilder-Samples/blob/main/experimental/sso-with-skills/RootBot/TokenExchangeSkillHandler.cs#L111) contains the same changes.

Last but not least, we did the following things apart from this Pull Request to have a consistency between TypeScript and C#:
- PR #3667: which applies these changes to the C# Virtual Assistant Sample
- [Commit](https://github.com/microsoft/botframework-solutions/pull/3584/commits/b6b54057a5b4b85f8466750ae06be781bada4b5c) of PR #3584: which applies these changes in TypeScript for a parity with C#

**Comment by Batta32** [comment] 2020-10-08 18:42
Hi @GitDruid - we are finalizing a plan to release new packages that will include the PR #3655 and PR #3667. As soon as we have any update we will back to you 😊.

**Comment by stevengum** [comment] 2020-10-19 17:27
@batta32, @ryanlengel, @peterinnesmsft any updates on this issue or the associated PRs? #3655 #3667

**Comment by Batta32** [comment] 2020-10-19 18:46
Hi @stevengum, we created the PR #3686 that duplicates the changes of the PR #3655. As soon as it's merged, this issue will be closed.

Last but not least, the PR #3667 was already merged.

**Closed as completed** 2020-10-19 19:40 UTC
Labels: customer-reported, customer-replied-to, Bot Services
