### ISSUE TITLE
Calendar skill skipping prompts in some scenarios

### ISSUE THREAD

**Issue by garypretty** [microsoft/botframework-solutions#751] opened 2019-02-10 16:11 UTC
**Project**
Virtual Assistant

**Description**
When using the calendar skill, if you say "schedule a meeting", the skill will then prompt for each piece of required information (i.e. title, content, attendees, time).  However, if you provide any information in the initial utterance, e.g. "schedule a meeting with chris" providing an attendee, the skill doesn't ask for some items. e.g. meeting title, meeting content, duration.

Is this by design??  It seems that the logic the skill is using is checking createHasDetail property (indicating some detail was passed with the initial utterance) and if this is true it is skipping certain properties.

**To Reproduce**
Enter "schedule a meeting with chris" and follow the prompts - default title / content / duration is used.

**Expected behavior**
I think that the skill should only skip over information already provided, but should prompt for anything that is missing.

I am happy to submit a PR for the above if this is not being done by design.

**Comment by garypretty** [comment] 2019-02-10 19:36
@lauren-mills Looking into this a little further, I can now see that certain fields seem to have been designed to revert to a default if they are not specified in the initial query - namely duration (default 0.5 hours), title (defaults to a value within CreateEventWhiteList.json) and meeting location and meeting content.

Whilst I cen see why this might be useful / required by some customers / scenarios, I think this is confusing for somebody picking up the virtual assistant and provides an inconsistent experience depending on what the user initially enters.

I can see three options here for addressing this;

1. Strip out the functionality where certain fields default - this would simplify the skill logic, but would still allow people using the solution to customise if needed. **This would be my preferred approach and is in line with the expected behavior I have detailed above**

2. Add flags for each of these properties to allow them to use default values or not and make the approach consistent. e.g. Move the default duration into the JSON file with the default event title (right now the default duration is hardcoded). Then add flags into the JSON file for useDefaultEventTitle. **This would allow the existing experience to be maintained, but would make it much easier to disable this 'default property' behavior**.

3. Leave things exactly as they are.

Hope you don't mind me dropping some ideas over for this - like I said, if we can agree if there are changes to be made then I am happy to help do the work and submit a PR.

**Comment by lauren-mills** [comment] 2019-02-10 20:17
This is definitely good feedback, and I agree its confusing not to prompt consistently. We've had some input from customers on these flows and it might be that this is a specific request that we need to rethink for the broader audience.

**Comment by bobokids** [comment] 2019-02-26 09:07
Assigned to myself. This behavior is by design. I will follow up.

**Comment by darrenj** [comment] 2019-04-02 16:08
@bobokids - I think this behaviour should be configurable.

**Comment by darrenj** [comment] 2019-04-25 07:15
@bobokids could we explore option 2 detailed above please?

**Comment by darrenj** [comment] 2019-06-10 19:58
In progress.

**Closed as completed** 2019-06-26 07:57 UTC
Labels: Type: Bug
