### ISSUE TITLE
update_cognitive_models.ps1 needs to be fixed to avoid overriding LUIS service classes

### ISSUE THREAD

**Issue by saikumaru** [microsoft/botframework-solutions#3615] opened 2020-08-13 13:32 UTC
#### What project is affected?
All the projects which use multiple cultures and need cognitive models updated.
This affects building of GeneralLuis.cs and DispatchLuis.cs

#### What language is this in?
powershell

#### What happens?
The LUIS Class files are not updated as expected, when we run
> .\Deployment\Scripts\update_cognitive_models.ps1 -LocalToRemote
w

#### What are the steps to reproduce this issue?
Run **.\Deployment\Scripts\update_cognitive_models.ps1 -LocalToRemote** for two cultures(say, Culture-1 has 6 intents, Culture-2 has 5 intents). With one culture having one lesser intent than the another.

or, run the command ".\Deployment\Scripts\update_cognitive_models.ps1 -LocalToRemote" and the DispatchLuis.cs is updated with only one of the culture's names, especially evident if you have QnA KBs for different languages.

#### What were you expecting to happen?
We expect the resultant class file having a superset of intents across these cultures

#### Can you share any logs, error output, etc.?
The resultant class is updated for Culture-1 when "bf luis:generate:cs" runs, and then again gets overwritten when ran for Culture-2 when "bf luis:generate:cs" runs.

This part of the script is what causes the issues

>        # Update each luis model based on local LU files
        foreach ($luisApp in $models.languageModels) {
            $lu = Get-Item -Path $(Join-Path $luisFolder $langCode "$($luisApp.id).lu")
            UpdateLUIS `
                -luFile $lu `
                -appId $luisApp.appid `
                -endpoint $luisApp.endpoint `
                -subscriptionKey $luisApp.authoringKey `
                -culture $langCode `
                -version $luisApp.version `
                -log $logFile

             if ($useLuisGen) {
                Write-Host "> Running LuisGen for $($luisApp.id) app ..." -NoNewline
                $luPath = $(Join-Path $luisFolder $langCode "$($luisApp.id).lu")
                RunLuisGen `
                    -luFile $(Get-Item $luPath) `
                    -outName "$($luisApp.id)" `
                    -outFolder $lgOutFolder `
                    -log $logFile
                Write-Host "Done." -ForegroundColor Green
            }

#### Any screenshots or additional context?
no

**Comment by peterinnesmsft** [comment] 2020-08-17 20:33
@saikumaru thanks for reporting this. I've done an initial assessment of this issue and agree with what is outlined here. We will move this into our planning backlog and determine prioritization and scheduling for our next release.

**Comment by peterinnesmsft** [comment] 2020-08-19 17:03
@saikumaru apologies for the delays - I am prioritizing this and will provide an update later today.

**Comment by peterinnesmsft** [comment] 2020-08-20 05:16
@saikumaru, just to follow up as promised. We currently have a number of items on our plate at the moment , but this otherwise looks like fair game. As I mentioned previously, we will add this to our backlog and work on this as part of our next release target. Will provide more information when we determine scheduling - watch this issue for updates.

**Comment by saikumaru** [comment] 2020-08-20 07:32
Thank you @peterinnesmsft , yes that would help. If you have any interim fix, please do keep me updated on that.

**Comment by peterinnesmsft** [comment] 2020-09-02 19:39
@lauren-mills, can you please do an initial assessment as to what you believe the right steps are for addressing this issue? I can work with you offline lock on details and we can find an owner to drive implementation.

**Comment by lauren-mills** [comment] 2020-09-08 17:45
There is not a great way of doing this right now, but it makes sense. The luis:generate CLI tool takes a .luis file as the input for the .cs file it creates, so currently the DispatchLuis.cs file is based on whatever the dispatch model is for the last locale in the parameters list. In order to create a .cs file that is a superset of all the various dispatch models, we would need to have a .luis file that includes all the intents from each dispatch model, then pass that into luis:generate.

**Comment by lauren-mills** [comment] 2020-09-08 18:25
We could use the dispatch CLI to create a placeholder .dispatch file that we would not actually deploy but could then be used as an input for the luis:generate command.

**Comment by saikumaru** [comment] 2020-09-16 14:10
@lauren-mills  I liked the solution, would you have a date when you plan to add that fix?

**Comment by cwhitten** [comment] 2020-11-09 19:32
@peterinnesmsft is this still being worked on?

**Comment by peterinnesmsft** [comment] 2020-11-10 18:57
We are not actively working on this - this is currently in the backlog and will need to revisit this as scheduling allows. I would anticipate this would come as part of next release cycle at the earliest.

**Comment by GitDruid** [comment] 2020-11-12 12:54
Hi all,
I'd like to add a note that could seems redundant but... just to be more precise.

The issue does not only affects the generation of GeneralLuis.cs and DispatchLuis.cs in the main Bot but it also **affects the single Skill project** while generating the **MySkillNameLuis.cs** file.

Just as an example I faced this issue in these days while working on a 3 language skill (EN, IT and DE) where I decided to use **datetimeV2** prebuilt entity.
Since datetimeV2 is still not supported in IT and DE (*) I ended up using it only in the EN model, and so with having differences in the 3 .LU files.
When update_cognitive_models runs, it will generate the MySkillNameLuis.cs file with datetimeV2 information while processing the EN language, then it will overwrite the file when processing IT and DE versions.

So... just to advice to not focus only on the dispatcher, since the issue is at a "lower" level also.

(*) = someone knows why? Or when it will be supported?

Ciao,
Alessandro.

**Comment by taicchoumsft** [comment] 2020-12-16 19:22
Hi @chrimc62 , can you advice how would you like to proceed with this datetimeV2 issue?

**Comment by chrimc62** [comment] 2021-01-06 03:14
The simplest fix for this is to generate a different class for each natural language.  The datetime vs datetimev2 recognizers are actually different and generate different results so there is no great way to merge them.  

For the intents, just generate the class for the model you consider the superset and don't generate for the others.  There is no way for us to know which model that might be so it is something you would have to do manually.

**Comment by LeeParrishMSFT** [comment] 2021-01-19 19:28
Close due to inactivity.

**Closed as completed by LeeParrishMSFT** 2021-01-19 19:28 UTC
Labels: customer-reported, customer-replied-to, Bot Services, approved, backlog, bug, Team: Virtual Assistant
