### ISSUE TITLE
[EnterpriseTemplate] Build pipeline for enterprise template/bot

### ISSUE THREAD

**Issue by lzc850612** [microsoft/botframework-solutions#889] opened 2019-02-28 21:36 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
We need to setup the build pipeline for enterprise template and enterprise bot that's built off of the enterprise template

**Describe alternatives you've considered**

**Additional context**

**Comment by darrenj** [comment] 2019-04-25 06:57
Dupe of #932

**Closed as completed by darrenj** 2019-04-25 06:57 UTC
