### ISSUE TITLE
Passing Data from skills bot to root bot without using dialogs

### ISSUE THREAD

**Issue by ambuj74** [microsoft/botframework-solutions#3666] opened 2020-09-25 11:36 UTC
0

I have 2 skills connected to a RootBot, and I am trying to invoke Skill B from Skill A (at the end of Skill A, and with no further action by the user). I know that I have to go through the RootBot for that. I have a problems to handle:

Passing data from Skill A -> RootBot

if i can pass data from skill A to Rootbot i can Pass data from RootBot-> Skill B

I'm using below snippet to call skill from root bot

`var response = await _skillClient.PostActivityAsync(_botId, targetSkill, _skillsConfig.SkillHostEndpoint, turnContext.Activity, cancellationToken);`

I'm using below snippet to end conversation in skill bot
`var endOfConversation = Activity.CreateEndOfConversationActivity();
endOfConversation.Code = EndOfConversationCodes.CompletedSuccessfully;`

is it possible to pass data from skills to bot without using dialogs

**Comment by ambuj74** [comment] 2020-09-25 15:36
@darrenj  can you please help

**Comment by sgellock** [comment] 2020-09-25 19:35
@ambuj74 are you using the virtual assistant solution accelerator?

**Comment by gabog** [comment] 2020-09-25 22:06
Hi @ambuj74, you can use the value property of the activity to pass parameters to a skill something like:

```
turnContext.Activity.Value = JObject.Parse("{ \"origin\": \"New York\", \"destination\": \"Seattle\"}");
var response = await _skillClient.PostActivityAsync(_botId, targetSkill, _skillsConfig.SkillHostEndpoint, turnContext.Activity, cancellationToken);
``` 

Also, if you want to return values when your skill completes, you can use the Value property for the EndOfConvesation activity:

```
var endOfConversation = Activity.CreateEndOfConversationActivity(); 
endOfConversation.Code = EndOfConversationCodes.CompletedSuccessfully;
endOfConversation.Value = JObject.Parse("{ \"origin\": \"New York\", \"destination\": \"Seattle\"}"); 
```

This is the mechanism we use internally in the dialogs to receive and return parameters. 

Does this help?

**Comment by KoradaRajesh** [comment] 2020-09-26 08:32
@gabog The Value parameter does not exist in endofConversation

![image](https://user-images.githubusercontent.com/51915291/94336427-dc3e4300-0000-11eb-890c-e8a346e5c8ae.png)

**Comment by gabog** [comment] 2020-09-26 19:31
Hi @KoradaRajesh, my snippet above is wrong, use this approach to create the eocActivity instead (setting locale is optional but you may want to set it if you support multiple languages): 

```
var endOfConversation = new Activity(ActivityTypes.EndOfConversation)
{
    Value = result.Result, 
    Locale = turnContext.Activity.Locale, 
    Code = EndOfConversationCodes.CompletedSuccessfully
};
``` 

The issue is that Activity.CreateEndOfConversationActivity returns an IEndOfConversationActivity which doesn't expose the Value property. We couldn't add Value to IEndOfConversationActivity (or IActivity) without breaking backward compat but the framework will accept the Activity instance and understand it as an EoC as long as the type is set correctly.

**Comment by KoradaRajesh** [comment] 2020-09-26 20:38
@gabog  But It's not returning the value what I'm passing in EndofConversationActivity
![image](https://user-images.githubusercontent.com/51915291/94349857-45a46d00-0066-11eb-862a-368c1f01b097.png)

![image](https://user-images.githubusercontent.com/51915291/94349762-4ab4ec80-0065-11eb-8ab8-a2e11e478bc5.png)

This result is getting in turncontext of OnTurnAsync and OnEndOfConversationActivityAsync methods but in OnMembersAddedAsync I got it like null

I want to handle flow base on this value in OnMembersAddedAsync method

**Comment by gabog** [comment] 2020-09-27 17:38
I'm not sure I understand your scenario @KoradaRajesh, can you please provide more context on what you are trying to do? What type of bot you are you trying to create, what channel are you targeting, what does the skill and the root bot do, what do you expect to do in OnMemebersAddedAsync, do you want to handle this on the skill or the root bot, etc.

As you already noticed the result for EoC will be in OnTurnAsyc, (or the EndEndOfConversationActivityAsync) you can capture the value there and use it somewhere else but that would be tied to your bot's logic.

**Comment by ambuj74** [comment] 2020-09-29 16:00
@gabog here the scenario is i have a root bot where I have used a Luis dispatcher and 2 skills bot (i.e. HR and IT) when root bot is getting an utterance it is hitting to dispatcher and if question is regarding IT its going to IT skills, if question is regarding HR it is going to HR skills, and I am also using separate Luis cognitive service in both the skill i.e. one for IT and another  for HR, now my problem is  if the conversation is going in IT skills and user gave an utterance related to HR then it will hit none intent in IT bot and there i am ending the conversation from IT bot and sending last utterance to Root bot and trying to call the HR bot by triggering dispatcher.

here I am not able to pass the last utterance which triggered none intent from skills bot(Here IT skills) to root bot after ending the whole conversation from IT skills. so that using that utterance it will trigger dispatcher and go to HR skills.

**Comment by gabog** [comment] 2020-10-12 19:09
Hi @ambuj74, it looks like a complex scenario, would you be able to provide a small code sample that showcases the issue? I am not sure how much you customized the original solution. In general, you could try to return a special value in your end of conversation that tells the rootbot to start a dialog with another skill but we would need a sample project so we can narrow this down (if we can remove dispatcher and LUIS from the equation that would make things simpler).

**Comment by cleemullins** [comment] 2020-10-22 18:21
@ambuj74, are you able to provide a bit more detail as @gabog has asked?

**Comment by CezaryMarcjan** [comment] 2020-11-02 18:25
Closing due to no activity. Please reactivate if a follow up is needed.

**Closed as completed by CezaryMarcjan** 2020-11-02 18:25 UTC
Labels: Support, customer-reported, customer-replied-to, Bot Services
