### ISSUE TITLE
Cancel and begin a dialog inside of InterruptDialogAsync doesn't start the MainDialog again

### ISSUE THREAD

**Issue by lshade** [microsoft/botframework-solutions#3298] opened 2020-04-21 20:00 UTC
#### What project is affected?
Virtual Assistant

#### What language is this in?
C#

#### What happens?
Similar issue to [this one](https://github.com/microsoft/botframework-solutions/issues/3267), but I want to start a dialog in the Interruptible method, have it cancel all other dialogs, and have it also finish by starting the MainDialog again.

In the `InterruptDialogAsync`, I have:
```
 // Cancel all dialogs on the stack.
 await innerDc.CancelAllDialogsAsync(cancellationToken);
 // Call Startup Dialog
 await innerDc.BeginDialogAsync(nameof(StartupDialog);
 interrupted = true;
 return interrupted;
```

Since I'm not restarting the InitialDialogId, once the StartupDialog has ended, the first user message  to the VA doesn't get a response. The user has to send it a second time to get a response.

#### What are the steps to reproduce this issue?
Cancel all dialogs and start a different dialog in the MainDialog's `InterruptDialogAsync` (see above code snippet.)

#### What were you expecting to happen?
After the dialog I called in the `InterruptDialogAsync` has ended, the first user's message to the VA should get handled by the MainDialog's `RouteStepAsync`.

**Comment by pavolum** [comment] 2020-04-21 20:04
So the solution is to end your StartupDialog with the following:
```
return await sc.ReplaceDialogAsync(nameof(MainDialog));
```
instead of
```
return await sc.EndDialogAsync();
```

What is happening now is...
StartupDialog ends with sc.EndDialogAsync and the dialog stack is empty since all parent dialogs were canceled prior to calling that dialog. When the dialog stack is empty, the next message to come in is programmed to start a maindialog instance, which it does, but your main dialog ignores the user text and does a silent prompt, as far as the user is concerned their query was ignored, then the next query comes in and is routed accordingly. 

If the dialog instead ends in replacedialogasync() then that will actually add maindialog to the stack and call the onbegin function of main dialog which should then route to the silent prompt. Then the next text to come in should be routed to the right place.

**Comment by pavolum** [comment] 2020-04-21 20:07
@lshade has confirmed offline that the above solution resolves the issue, so I am closing the issue out now.

**Closed as completed by pavolum** 2020-04-21 20:07 UTC
Labels: customer-replied-to
