### ISSUE TITLE
404 error from Skill/ReplyToActivity [activityId/conversationId] endpoint while running VA solution

### ISSUE THREAD

**Issue by manish-95** [microsoft/botframework-solutions#3301] opened 2020-04-22 06:55 UTC
#### What project is affected?
Virtual Assistant, Skills (version 0.8 Beta)

#### What language is this in?
C#

#### What happens?
I have a Virtual Assistant Bot connected to a Skill Bot. When I send messages from the VA to the Skill, I notice constant 404 failures in the Skill/ReplyToActivity [activityId/conversationId] endpoint. I have also noticed that the conversation id gets appended with '-directline-skillconvo' , something that was not happening before.

#### What are the steps to reproduce this issue?
1. Connect VA and Skill Bot
2. Access a Skill from the VA, through Webchat.
3. Note error from logs.

#### What were you expecting to happen?
The 404 error should not occur.

#### Can you share any logs, error output, etc.?

Request name | POST Skill/ReplyToActivity [activityId/conversationId] |  
-- | -- | --
Response code | 404 |  
Successful request | false |  
Response time | 8.1 ms |  
Request URL | https://emcee-beta-fq33t5e.azurewebsites.net/api/skills/v3/conversations/HOjzX7xth2VBrkIgBw6OaP-c-directline-skillconvo/activities/HOjzX7xth2VBrkIgBw6OaP-c\|0000003

**Comment by darrenj** [comment] 2020-04-22 09:08
Morning - Can you confirm the SkillHostEndpoint config setting in your VA Bot is set correctly? This should be pointing at your VA Bot which the Skill calls back to. This config setting is used by the Skill so good to check. Also if you are debugging a VA say locally, pointing to a remote Skill you'll need to ensure [ngrok](https://microsoft.github.io/botframework-solutions/help/known-issues/#http-500-error-when-invoking-a-skill) is configured correctly.

```json
    "skillHostEndpoint": "https://yourVAAppService.azurewebsites.net/api/skills"
```

It looks from your log above that it likely is set correctly but just checking! If so - can you confirm the BF SDK versions used by your VA + Skill please?

**Comment by manish-95** [comment] 2020-04-22 09:34
@darrenj Hi, just verified that the SkillHostEndpoint is set correctly. The version I am using in both the VA as well as the Skill is 4.7.2

**Comment by lzc850612** [comment] 2020-04-22 16:11
@manish-95 is it possible to share us your source code so we can help you debug to see what's going on?

**Comment by lzc850612** [comment] 2020-04-22 16:12
and what channel are you using? is it webchat with directline?

**Comment by manish-95** [comment] 2020-04-23 05:05
@lzc850612 That's right, I am using WebChat with directline. As for the source code, it is the same as the ones available as part of the VA and Skill templates in this repo. Would you still require the source code ?

**Comment by manish-95** [comment] 2020-04-23 05:23
@lzc850612 Forgot to mention, I have made a few changes to include proactive notifications following the instructions provided [here](https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/enable-proactive-notifications/4-virtual-assistant/)

**Comment by lzc850612** [comment] 2020-04-23 05:32
Can you pack up your source code and share with me so i can use the exact same code to debug? Please send it to my email address tedlee@microsoft.com so i can debug to see the exact issue. Thanks.

**Comment by manish-95** [comment] 2020-04-23 05:36
Would you require code for both the VA as well as the Skill?

**Comment by lzc850612** [comment] 2020-04-23 05:36
Both VA and skill please

**Comment by manish-95** [comment] 2020-04-23 05:49
@lzc850612 I've sent an email to the address you gave me, containing a link to the source code.

**Comment by lzc850612** [comment] 2020-04-23 05:58
Perfect. I'm able to access the code. I'll debug and get back to you.

**Comment by manish-95** [comment] 2020-04-23 05:59
Alright, Thanks a lot!

**Comment by lzc850612** [comment] 2020-04-23 06:26
does this mean it's working fine?
![Capture](https://user-images.githubusercontent.com/4001684/80066277-7e0cb180-84f0-11ea-8ed1-ece5a643afbc.PNG)

can you send me the utterances you used to reproduce your issue?

one thing i want to throw out there that i'm suspecting could be wrong is, when you debug VA<->skill locally, you need to change the SkillHostEndPoint to be the local VA endpoint (with localhost:port), instead of the one in azure, and i suspect your azure VA doesn't have the latest VA bits which is why the 404. When i'm debugging i'm using localhost for both skill and VA, and it seems to be working fine.

**Comment by manish-95** [comment] 2020-04-23 06:52
@lzc850612 I face the issue when trying to invoke the Skill with the deployed versions of both VA and skill. In some cases, it just shows up as a failed dependency in the logs, however, in other cases, it completely halts the rest of the flow. I tried with the same utterance you did, and was able to get the error.

**Comment by manish-95** [comment] 2020-04-23 06:54
I also see a cancelled request from the Skill logs, going back to the endpoint of the VA as per the config.

**Comment by manish-95** [comment] 2020-04-23 06:58
@lzc850612  Attaching a screenshot, showing the two different 404 requests.
![image](https://user-images.githubusercontent.com/29098159/80068788-d75efa00-855d-11ea-8099-a9b49a0a2037.png)

**Comment by lzc850612** [comment] 2020-04-23 21:48
Ok let's try a few things:
1. Please run VA and Skill locally, and update the SkillHostEndpoint and the skill's endpoint to be both local. See if you still run into this issue
2. When you're running into the error with deployed VA and skill, are they both deployed? Are you seeing an error message when 404 happens? Are you able to reproduce this issue 100%?
3. Have you tried using your VA against an pre-built skill such as Calendar or Email from our repo?

If VA and Skill can run locally without issue, then we can isolate the problem to something wrong with deployed VA and Skill.

**Comment by shilsmarty** [comment] 2020-04-24 03:14
This is exactly happening with the solution i have with VA <--> Skill.

It was working fine till few days back, then i upgraded all dependent nuget package to v4.8.0 (Microsoft.Bot.* packages.)

- VA and Skill both running in localhost.

- VA is able to identify right skill to invoke, and in appsetting.json skill is having localhost url.


Error :
![image](https://user-images.githubusercontent.com/10603878/80171176-81f70d00-859e-11ea-82fd-f583cb4778ab.png)

In AppInsight 
![image](https://user-images.githubusercontent.com/10603878/80171286-d1d5d400-859e-11ea-895e-1439738b5356.png)

Not sure what is changed, both VA and Skill endpoint are on http and not https.

Please help me out, looks similar problem to this one.

**Comment by shilsmarty** [comment] 2020-04-24 03:50
Thanks @darrenj and @lzc850612, my issue resolved after change in SkillHostEndpoint, based on your comment above.

Thanks

**Comment by lzc850612** [comment] 2020-04-24 03:52
So your SkillHostEndpoint was set incorrectly?

**Comment by shilsmarty** [comment] 2020-04-24 03:56
Yes, SkillHostEndpoint was pointing to http://**SkillbaseUrl**/api/skills.

**Comment by lzc850612** [comment] 2020-04-24 03:56
ok. Thanks for letting us know. Closing this issue.

**Comment by shilsmarty** [comment] 2020-04-24 03:57
@lzc850612 sorry, but i think this issue is raised by @manish-95, please verify with him, if he is unblocked.

**Comment by lzc850612** [comment] 2020-04-24 04:02
what was your issue?

**Comment by manish-95** [comment] 2020-04-24 04:58
@lzc850612 I am yet to try both locally, as well as with the Calendar skill, let me check with those and get back to you.

**Comment by manish-95** [comment] 2020-04-24 05:19
Hi, I've tried running VA+Skill locally, and am running into the same issue. The same is also in the case of VA + Calendar Skill, both accessed through the deployed version. Attaching screenshots.
VA+Skill Locally
![Local Bot](https://user-images.githubusercontent.com/29098159/80177357-228a1300-8619-11ea-9d1a-8ab16a340392.JPG)
VA+ Calendar Skill (Both deployed)
![CalendarSkill](https://user-images.githubusercontent.com/29098159/80177360-27e75d80-8619-11ea-946d-b1b34d45b864.JPG)

**Comment by lzc850612** [comment] 2020-04-24 16:21
Can you share the exact configuration you have when you're running locally? The appsettings.json on VA would suffice. You can share it on the same link you used earlier to share source code. When i ran VA + Skill locally it worked fine so i'm suspecting the configuration you're using might have some issue.

**Comment by manish-95** [comment] 2020-04-25 08:59
@lzc850612 I've shared the file via the same email thread.

**Comment by lzc850612** [comment] 2020-04-26 07:26
I can see that you're using ngrok for both VA and skill. If you're running them locally, can you change them to just the http://localhost:{portnumber} endpoint? I have in the past run into weird 4xx error when using ngrok so let's exclude the factor using ngrok from this testing first. Also when i test VA+Skill locally and it worked, i used just the localhost and didn't use ngrok. it's not necessary when you have both VA and Skill running locally.

**Comment by manish-95** [comment] 2020-04-27 07:20
Hi Ted, apologies for my delayed response. 
After changing the endpoints to point to the localhost endpoint, I still see the same failed requests.

![Local Bot- No ngrok](https://user-images.githubusercontent.com/29098159/80344744-b3fdbd00-8885-11ea-89d8-eaa020ddda59.JPG)

**Comment by lzc850612** [comment] 2020-04-27 17:36
How are you testing your local running VA + Skill? are you using Emulator for testing? are you getting any error in the emulator trace window? When I run local VA + skill with Emulator everything worked fine (like in my previous screenshot)

**Comment by manish-95** [comment] 2020-04-27 17:39
Yes, I'm testing via emulator. There is no error in the emulator trace window. However, there are cases where the 404 occurs and the message never carries through to the skill, or results in an error message in the VA.

**Comment by lzc850612** [comment] 2020-04-28 19:47
So you're saying that the issue doesn't always reproduce, it only reproduces in some cases right? when the error happens, can you copy over the errors you're seeing in emulator, particularly the errors you can see in the trace window of the emulator?

**Comment by manish-95** [comment] 2020-05-01 06:25
Oddly enough I don't see any errors popping up in the trace window of the emulator. Although I can still see them in the application logs.

**Comment by lzc850612** [comment] 2020-05-05 00:28
Can you confirm if you are seeing any issues in emulator testing, meaning that are you seeing the bot saying anything like 'there's an error' or something similar or just simply not responding? Let's try to isolate the potential issues. If there's no errors/issues when the bot responds, the 404 might be a total different issue.

**Comment by manish-95** [comment] 2020-05-05 05:24
Yes, sometimes, quite randomly, an ongoing conversation will simply stop when a 404 error occurs. This usually happens when I send a message, and do not receive a response due to the 404. If I attempt to send the message again, I get a 'Sorry, something went wrong message'.

**Comment by darrenj** [comment] 2020-05-20 08:29
When reviewing this, if it’s an intermittent error and ngrok is being used I do wonder whether its a transitory error. We do strange connectivity errors from time to time with ngrok, especially when many messages are being exchanged. If it works most of the time I would strongly advise you register with ngrok (free) and then register the provided authtoken giving you more messages which is likely to resolve ngrok related intermittent messages.

Alternatively you can publish your bot + skill to azure and extensively test, if you see a repeat of the message without ngrok please reopen and let us know.

**Closed as completed by darrenj** 2020-05-20 08:29 UTC
Labels: Type: Bug, customer-reported, customer-replied-to, Bot Services
