### ISSUE TITLE
Latest VA automotive skill does not work "out of the box"

### ISSUE THREAD

**Issue by joelhulen** [microsoft/botframework-solutions#944] opened 2019-03-06 22:01 UTC
## Project

**Name**: Virtual Assistant, Automotive Skill

**Language**: C#

## Description

I have cloned the AI repo, which includes the latest commit that references all 4.3.1 versions of the Microsoft.Bot NuGet packages. I have not made any code changes at this point. All I've done is run the `PowerShell.exe -ExecutionPolicy Bypass -File DeploymentScripts\deploy_bot.ps1` script from the `\AI\solutions\Virtual-Assistant\src\csharp\skills\automotiveskill\automotiveskill` directory, which successfully created the `.bot` files in the root and LocaleConfigurations directories, then updated the `appsettings.json` file with the path to the `.bot` files and the generated bot secret.

When I debug my AutomotiveSkill project and then open my bot file in the Bot Framework Emulator, ensuring the development endpoint is selected (http://localhost:3980/api/messages), I keep receiving 400 error codes anytime I send a message to my bot.

Here is a sample log output:

```bash
[16:45:32] POST 201 directline.startConversation
[16:45:32] Emulator listening on http://localhost:44764
[16:45:32] ngrok not configured (only needed when connecting to remotely hosted bots)
[16:45:32] Connecting to bots hosted remotely
[16:45:32] Edit ngrok settings
[16:45:35] ->message hi
[16:45:35] POST 400 directline.postActivity
```

Clicking on the POST for my 'hi' message shows this in the inspector:

```javascript
{
  "channelData": {
    "clientActivityID": "15519087354600.u5dlk4ersfa"
  },
  "channelId": "webchat",
  "entities": [
    {
      "requiresBotState": true,
      "supportsListening": true,
      "supportsTts": true,
      "type": "ClientCapabilities"
    }
  ],
  "from": {
    "id": "r_8is9ukthwd",
    "role": "user"
  },
  "locale": "en-us",
  "text": "hi",
  "textFormat": "plain",
  "timestamp": "2019-03-06T21:45:35.460Z",
  "type": "message"
}
```

Clicking on 400 shows this in the inspector:

```javascript
{
  "error": {
    "code": "ServiceError",
    "message": "Refresh access token failed with status code: 401"
  }
}
```

![image](https://user-images.githubusercontent.com/5950304/53916967-76125980-4031-11e9-872b-1bb9144f53db.png)

I am not sure how to debug this. I've tried redeploying several times just in case. Any hints on where I can look or steps to debug?

## To Reproduce

1. Clone the solution.
2. Run the `PowerShell.exe -ExecutionPolicy Bypass -File DeploymentScripts\deploy_bot.ps1` script from the `\AI\solutions\Virtual-Assistant\src\csharp\skills\automotiveskill\automotiveskill` directory.
3. Copy the generated bot file secret.
4. Update `appsettings.json` with the paths to the `.bot` file in the root (the script should've done this for you) and LocaleConfigurations directories, then update the file with the generated bot secret for both bot files.
5. Debug the AutomotiveSkill project in Visual Studio.
6. Open the bot file that was generated and saved to the root of the AutomotiveSkill project in the Bot Framework Emulator, ensuring the development environment is selected.
7. Type in any message, such as 'hi'.

## Expected behavior

A welcome screen should be displayed in response, and any message I type in should succeed.

**Comment by joelhulen** [comment] 2019-03-07 13:28
I figured it out!

I noticed that the `development` `endpoint` within the bot file had values in both `appId` and `appPassword`. I had to remove these values:

```javascript
{
            "type": "endpoint",
            "id": "1",
            "name": "development",
            "appId": "",
            "appPassword": "",
            "endpoint"
}
```

Now it works! That said, you probably need to update the bot generation script to keep these two values empty for the development endpoint.

**Comment by joelhulen** [comment] 2019-03-07 13:37
Now the problem that I'm seeing is that each `luisResponse` results in an error message in the chat window stating, "No renderer for this activity." Is this to be expected?

![image](https://user-images.githubusercontent.com/5950304/53960380-2aed5a80-40b4-11e9-93c3-46ac1e0901fe.png)

**Comment by lauren-mills** [comment] 2019-03-07 17:29
The "[LUIS] (intermediate value).map is not a function" message is actually just a UI rendering bug in the emulator and isn't referencing anything to do with the bot or LUIS instance itself.

**Comment by lauren-mills** [comment] 2019-03-07 17:46
Hey @joelhulen this is a bug in the emulator and should be fixed in an upcoming release. You can follow the bug progress here https://github.com/Microsoft/BotFramework-Emulator/issues/1347

**Comment by joelhulen** [comment] 2019-03-07 18:17
Thank you, @lauren-mills! How can I disable tracing in the meantime?

Also, are you tracking on the issue and workaround I found above?

**Comment by darrenj** [comment] 2019-03-07 18:23
You can't disable tracing unfortunately, should be fixed in the next daily build for the emulator.
As for the appId and appPassword - these are populated as part of deployment and are critical for operation so not sure why they were causing issues?

Did you run msbot clone services to deploy? Assume you have a resource group in azure with a bot instance created?

**Comment by joelhulen** [comment] 2019-03-07 19:01
@darrenj I only removed the `appId` and `appPassword` values from the development endpoint (localhost). I could not get it to work with the emulator until I removed those values. I kept the values in place for the production endpoint.

I did run the `msbot clone services` command via the `DeploymentScripts\deploy_bot.ps1` PowerShell script:

`PowerShell.exe -ExecutionPolicy Bypass -File DeploymentScripts\deploy_bot.ps1`

So yes, I have the resource group with all of the required services within.

That said, I am unable to actually publish the bot. I executed the generated deployment command:

`az bot publish --resource-group [REDACTED] -n [REDACTED] --subscription [REDACTED] -v v4 --proj-name "AutomotiveSkill.csproj"`

The error I receive is: `Deployment failed. To find out more information about this deployment, please visit https://[REDACTED]/api/deployments/5b6dea00419e48df9ab22018dfdfcc80`.

This error occurs whether or not I have the appId and appPassword values in the development endpoint.

**Comment by darrenj** [comment] 2019-03-13 09:35
OK - thanks. appId and appPassword should be populated even for the development endpoint so not sure why the emulator was causing you issues. Will ask our support team to see if they can repro

**Comment by CoHealer** [comment] 2019-03-13 23:07
@stevkan, can you please assist?

**Comment by stevkan** [comment] 2019-03-14 22:44
@joelhulen, @darrenj Attempting to repro. Will post results as soon as I have them.

**Comment by mdrichardson** [comment] 2019-03-19 15:55
@joelhulen 	@darrenj 	I took this ticket over from @stevkan. I was unable to reproduce this, following @joelhulen's steps. Really, the only "issue" I could reproduce was needing to add the path to my `localeConfigurations` `.bot` file. My `root` `.bot` was automatically added to `appsettings.json`.

I was also able to successfully publish.

That being said, there were [some pretty significant commits](https://github.com/Microsoft/AI/commits/master/solutions/Virtual-Assistant/src/csharp/skills/automotiveskill/automotiveskill) made in the last week that may have fixed this issue.

![image](https://user-images.githubusercontent.com/40401643/54619026-34b27e80-4a21-11e9-856d-49b84c739f9a.png)

![image](https://user-images.githubusercontent.com/40401643/54619045-3da35000-4a21-11e9-8738-0b52f04f56e8.png)

![image](https://user-images.githubusercontent.com/40401643/54621093-6da02280-4a24-11e9-880c-ceb867894c0c.png)

**Comment by joelhulen** [comment] 2019-03-21 15:53
@mdrichardson I synced with the latest version of the repo and I still am able to reproduce the issue. There may be one difference in my environment in that I first create the Azure App and supply its ID and secret to the deployment script (\AI\solutions\Virtual-Assistant\src\csharp\skills\automotiveskill\automotiveskill\deploy_bot.ps1).

This is because the script always fails trying to create an Azure App for me.

**Comment by mdrichardson** [comment] 2019-03-21 15:54
@joelhulen What error are you getting during deployment? I see the one you posted above, but is there relevant info if you visit the link?

**Comment by mdrichardson** [comment] 2019-04-01 15:11
@joelhulen 	Are you still able to reproduce this? Can you copy/paste the error output from the link that gets included in the "Deployment failed" error? Also, before deploying, please ensure you're using the latest [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) and msbot (`npm i -g msbot`)

**Comment by mdrichardson** [comment] 2019-04-05 14:48
I am closing this issue as it doesn't seem to be a blocking issue. Feel free to reopen if you have need to get this resolved.

**Closed as completed by mdrichardson** 2019-04-05 14:48 UTC
Labels: Type: Bug, Support
