### ISSUE TITLE
System.ArgumentException observed in MainDialog.cs using sample VA

### ISSUE THREAD

**Issue by davidmcgowan** [microsoft/botframework-solutions#3574] opened 2020-07-21 12:18 UTC
#### What project is affected?
VA Sample (Potentially calendar skill sample)

#### What language is this in?
C#

#### What happens?
In Teams, when two skills which require authentication are linked to VA, a `System.ArgumentException`
is observed after successful login (SSO enabled).

#### What are the steps to reproduce this issue?
VA setup with skill requiring authentication linked and installed in Teams.

#### What were you expecting to happen?
Skill dialog continues.

#### Can you share any logs, error output, etc.?
``System.ArgumentException: An item with the same key has already been added. Key: BotFrameworkAdapter.InvokeResponse
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.Bot.Builder.TurnContextStateCollection.Add[T](String key, T value)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass25_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at SampleVA.Dialogs.MainDialog.StoreOutgoingActivitiesAsync(ITurnContext turnContext, List`1 activities, Func`1 next) in D:\a\r1\a\_eva\build-artifact\eva\Dialogs\MainDialog.cs:line 462
   at Microsoft.Bot.Solutions.Middleware.SetSpeakMiddleware.<>c.<<OnTurnAsync>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.TranscriptLoggerMiddleware.<>c__DisplayClass3_0.<<OnTurnAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.<>c__DisplayClass7_0.<<OnTurnAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.SkillDialog.SendToSkillAsync(ITurnContext context, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.SkillDialog.ContinueDialogAsync(DialogContext dc, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)
   at SampleVA.Dialogs.MainDialog.OnContinueDialogAsync(DialogContext innerDc, CancellationToken cancellationToken) in D:\a\r1\a\_eva\build-artifact\eva\Dialogs\MainDialog.cs:line 161
   at Microsoft.Bot.Builder.Dialogs.ComponentDialog.ContinueDialogAsync(DialogContext outerDc, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.RunAsync(Dialog dialog, ITurnContext turnContext, IStatePropertyAccessor`1 accessor, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.ActivityHandler.OnInvokeActivityAsync(ITurnContext`1 turnContext, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Teams.TeamsActivityHandler.OnInvokeActivityAsync(ITurnContext`1 turnContext, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.ActivityHandler.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
   at SampleVA.Bots.DefaultActivityHandler`1.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in D:\a\r1\a\_eva\build-artifact\eva\Bots\DefaultActivityHandler.cs:line 44
   at Microsoft.Bot.Solutions.Middleware.EventDebuggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
   at Microsoft.Bot.Solutions.Middleware.SetLocaleMiddleware.OnTurnAsync(ITurnContext context, NextDelegate next, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.ShowTypingMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TranscriptLoggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.TelemetryInitializerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)``

#### Any screenshots or additional context?
latest versions of VA and Calendar skill samples being used.

**Comment by lauren-mills** [comment] 2020-07-21 18:15
Hi @davidmcgowan, I'm looking into this. Can you confirm it only happens when you have more than one skill connected to the VA?

**Comment by davidmcgowan** [comment] 2020-07-22 07:59
Great thanks.

I can confirm this happens with either 1 or more skills. The skill used to test was the calendar skill sample.

Also worth noting that the issue is not observed when testing in the emulator or webchat with SSO enabled.

**Comment by capri02** [comment] 2020-08-07 10:57
@lauren-mills  Is there any update on this? I am facing the same issue, but, using sample skill bot instead of calendar skill. SSO is also enabled.
Just for reference that is how the end-to-end transaction looks like in Azure telemetry for an aforementioned problem.

![end-to-end transaction](https://user-images.githubusercontent.com/6074308/89639528-02bbe980-d8ae-11ea-9709-23e47f3bd7ea.png)

**Comment by lzc850612** [comment] 2020-09-08 17:00
I'm setting up the environment to reproduce this issue. Will update once I have something

**Comment by davidmcgowan** [comment] 2020-09-22 09:02
Hello, have you been able to reproduce this issue?

**Comment by peterinnesmsft** [comment] 2020-10-19 21:42
Hi @davidmcgowan,

I've taken an initial look into this. I need to do some more digging to pinpoint exactly what path we're hitting in the underlying SDK code, but my first take is that this is a bug in the SDK - specifically, here: https://github.com/microsoft/botbuilder-dotnet/blob/3906c535b18978c475bb6bc7dc82590257f64fb8/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L539-L544

Based on your described scenario of having two skills connected, my initial suspicion is that we are getting into a state where we are triggering two Invoke activities (which is I believe used to communicate to connected Skills ultimately), and hitting the condition in the linked code within the adapter when the bot is attempting to send all of the activities created during its turn.

I'm going to continue digging to make sure I can pinpoint the exact conditions under which this is occurring, but I expect that we will transfer this issue to the microsoft/botbuilder-dotnet repo and have the SDK team take this one.

Apologies for the delays, and thanks for the continued patience while we investigate this!

**Comment by peterinnesmsft** [comment] 2020-10-29 17:55
Just to follow up on this, the SDK has now merged the necessary change that should address this underlying issue. Once a new version of the SDK has been released containing this fix, we will be sure to publish new versions of the Virtual Assistant templates that contain this fix.

We are currently targeting mid-November timeframe for the new SDK release, so expect our update to follow shortly after that.

**Comment by davidmcgowan** [comment] 2020-10-30 09:06
Many thanks @peterinnesmsft.

**Comment by mrivera-ms** [comment] 2020-11-10 19:19
This should be resolved with the latest version of the SDK 4.11.0.

**Comment by axelsrz** [comment] 2020-11-24 19:44
Closing this per last comment

**Closed as completed by axelsrz** 2020-11-24 19:44 UTC
Labels: customer-reported, customer-replied-to, Bot Services, approved, bug, Team: Virtual Assistant
