### ISSUE TITLE
Calendar login issue in teams

### ISSUE THREAD

**Issue by amoyalan20** [microsoft/botframework-solutions#3691] opened 2020-10-22 09:31 UTC
While integrating the calendar skill with teams facing an issue while authentication.(not able to login)After clicking the login button the authentication is not complete and when we type anything its throwing an error as attached in the screenshot.
![image](https://user-images.githubusercontent.com/73281779/96852792-33f09280-1477-11eb-80ee-5324b87bbaa0.png)
could you please suggest what steps are to be done for integrating calendar skill authentication in teams?

**Comment by Batta32** [comment] 2020-10-22 12:50
Hi @amoyalan20 , thanks for reporting this issue. We came up with some **questions** in order to narrow the issue and your environment:
1. Are you using the [Calendar Skill](https://github.com/microsoft/botframework-skills/tree/master/skills/csharp/calendarskill) of botframework-skills repository?
1. Are you using the Calendar Skill connected to a Virtual Assistant?
1. Have you tested the Authentication in another channel? For example [Bot Framework Emulator](https://github.com/microsoft/botframework-emulator).
1. Have you reviewed the Calendar [configuration](https://microsoft.github.io/botframework-solutions/skills/samples/calendar/#configuration) document?

We will back to you as soon as we have any update 😊.

**Comment by amoyalan20** [comment] 2020-10-23 11:07
When we are connecting the calendar skill directly to teams we are able to authenticate using the login button. But while connecting calendar skill  with the virtual assistant not able to login.
So we need to update any changes to virtual assistant code?

**Comment by peterinnesmsft** [comment] 2020-10-26 21:20
Hi @amoyalan20,

As a first step, I would suggest reviewing our documentation on connecting an existing skill sample to a virtual assistant and double-checking that you have not missed any steps, everything is configured as expected, etc. You can find our documentation located [here.](https://microsoft.github.io/botframework-solutions/skills/tutorials/add-prebuilt-skill/1-intro/)

For connecting your Virtual Assistant to Teams, I would suggest using the documentation found [here](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-for-teams#add-using-app-studio) to review, but it sounds like this piece is at least working.

Unfortunately, it's impossible to know specifically what issue you are having provided based on the limited information supplied in this issue without additional data. I would recommend looking into your Application Insights logs to look for any specific errors that may be of further use. Feel free to share that here, and we can help investigate further.

**Comment by xieofxie** [comment] 2020-10-27 04:48
Hi @amoyalan20 I have created a full check list for issues like this. https://github.com/microsoft/botframework-skills/blob/hualxie/checklist/docs/check_va_skill_oauth.md
It will help you to verify VA, skill & OAuth locally first, so we could find and identify the exception more easily.
Please check it and report any exception if you can't solve. Thanks!

**Comment by Batta32** [comment] 2020-10-27 18:49
Hi @xieofxie, we **confirm** that following the steps of the [document](https://github.com/microsoft/botframework-skills/blob/hualxie/checklist/docs/check_va_skill_oauth.md), the VA - Skill OAuth is correctly working.

However, using Microsoft Teams as the communication's channel, we **faced** the issue #3574 which is already solved with the merged microsoft/botbuilder-dotnet#4845; and should be fixed in the next release of the SDK (see attached gif).

@amoyalan20, please confirm that following the mentioned steps, the issue is solved.

_Authentication process in Microsoft Teams channel with Virtual Assistant - Calendar Skill_
![VASkillCalendarAuthTeamsReply](https://user-images.githubusercontent.com/11904023/97347755-fa030000-186b-11eb-886f-ea184b624de5.gif)

**Comment by Batta32** [comment] 2020-11-05 13:48
@peterinnesmsft - we can close the issue due to inactivity. @amoyalan20 if you are still experiencing issues, feel free to reactivate and we can pick this up again.

**Closed as completed** 2020-11-05 17:09 UTC
Labels: customer-reported, customer-replied-to, Bot Services, bug
