### ISSUE TITLE
[Documentation]Add documentation for setup CI/CD for Enterprise Template and VA

### ISSUE THREAD

**Issue by lzc850612** [microsoft/botframework-solutions#655] opened 2019-01-30 15:50 UTC
**Is your feature request related to a problem? Please describe.**
Add documentation for setup CI/CD for Enterprise Template and VA

**Describe the solution you'd like**
Customers need help setting up CI/CD for Enterprise Template + VA to have a better development & integration experience. We need to add documentation around that to provide guidance how to do that.

e.g.:
- [ ] Build Pipeline
- [ ] Refreshing Dispatch (via CLI?)
- [ ] Unit Tests
- [ ] Deployment

**Comment by mganeshphani** [comment] 2019-01-31 04:58
Thankyou @darrenj  I am following this issue now.. appreciate your quick responses.

**Comment by darrenj** [comment] 2019-03-05 14:10
Linked to #932

**Comment by darrenj** [comment] 2019-04-25 06:59
Dupe of #932 targeted for shortly after build

**Closed as completed by darrenj** 2019-04-25 06:59 UTC
