### ISSUE TITLE
Calendar Skill login Issue - The Sign In code was not found or expired. Please try asking the bot to sign in again.

### ISSUE THREAD

**Issue by gagankohli2000** [microsoft/botframework-solutions#3065] opened 2020-02-15 09:27 UTC
#### What project is affected?
Calendar skill and ITSM skill login issue when being accessed via VA

#### What language is this in?
Csharp

#### What happens?
I'm using ITSM and Calendar skill. Both are being access through VA over webchat and Teams channel.
I'm having token issues with both skill. They both run fine and suddenly one skill will have token issue.
While ITSM works fine on team and usually calendar skills give error sign-in code not found or expired.

On web chat calendar skill work fine but ITMS will give "Your login failed"

Here are the screenshots
![ITSMskillerror](https://user-images.githubusercontent.com/14933211/74585544-b1831980-5031-11ea-90c7-ea125b265e57.png)
![loginErrorOutlook](https://user-images.githubusercontent.com/14933211/74585545-b2b44680-5031-11ea-8383-2b2333f79a73.png)

**Comment by csnarain** [comment] 2020-02-17 11:35
I'm able to login successfully but it fails throws error (502 bad gateway - in browser inspect) after signin

**Comment by darrenj** [comment] 2020-02-18 15:59
Can you go into the Bot Registration entry in the Azure Portal. Go down to settings and find the Auth connection. For the Auth connection can you click test connection and validate this works?

**Comment by gagankohli2000** [comment] 2020-02-19 09:09
@darrenj 
![outlook1](https://user-images.githubusercontent.com/14933211/74818648-21a3df00-5353-11ea-8100-468519bd95c8.png)
Yes, Test connection is working fine. I'm facing this issue with Calendar skill when deployed on teams. Calendar skill is working fine on web chat.

I have enabled Meeting room booking on calendar skill. Not sure issue is occuring due to Treat application as a public client. Which is required for Meeting room booking.

**Comment by darrenj** [comment] 2020-02-19 10:37
The Treat application as a public client is a one time thing required for meeting room data extraction, I don't think it will be related.

I'm a little confused as above you have screenshots of WebChat/Emulator not working versus Teams.

Can I suggest the following:

- [ ] Test ITSM and Calendar Skill directly using emulator or webchat (not the azure portal web chat) and validate you can login
- [ ] Test VA directly using emulator or webchat (not the azure portal web chat) and validate you can login
- [ ] Ensure you've created a Manifest in Teams and side-loaded as per [these instructions](https://microsoft.github.io/botframework-solutions/clients-and-channels/tutorials/enable-teams/1-intro/) and not testing by clicking the Teams link in the Azure Bot Service channels page which will not work for authentication scenarios.

**Comment by csnarain** [comment] 2020-02-19 13:20
@darrenj - I already tried using the skills in Teams exactly as mentioned in the document but getting errors. See the screenshots below. More importantly look into the browser console errors

![image](https://user-images.githubusercontent.com/9998645/74841533-d4be0980-534e-11ea-8ca7-d4472a57d46c.png)


![image](https://user-images.githubusercontent.com/9998645/74837949-9c1b3180-5348-11ea-9eb2-d655f087f667.png)

**Comment by darrenj** [comment] 2020-02-19 22:45
Can I double check your DefaultActivityHandler implementation (under your Bots) folder as per [this](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Bots/DefaultActivityHandler.cs)

Specifically that your Implementation services from TeamsActivityHandler that adds additional capabilities for Teams including Auth handling.

```csharp
public class DefaultActivityHandler<T> : TeamsActivityHandler
        where T : Dialog
    {
```

**Comment by xieofxie** [comment] 2020-02-20 03:49
Hi @darrenj I tried this and found this is a bug caused by two issues:
* Sample skills are not using TeamsActivityHandler
* TeamsActivityHandler should overwrite OnTeamsSigninVerifyStateAsync like https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/46.teams-auth/Bots/TeamsBot.cs

Should I create a pr for this? Against master or next? Thanks

**Comment by csnarain** [comment] 2020-02-20 08:54
I also suggest that there should be some documentation on adding skills to Teams and debugging it locally. If there is already one, provide a link to the same pls.

**Comment by xieofxie** [comment] 2020-02-20 09:18
hi @csnarain, good point! 
Here is document about adding to Teams: https://microsoft.github.io/botframework-solutions/clients-and-channels/tutorials/enable-teams/1-intro/. 
I didn't find documents about debugging and we should add it.
Currently, you could use ngrok as in this https://microsoft.github.io/botframework-solutions/help/known-issues/

**Comment by csnarain** [comment] 2020-02-22 07:16
hi @xieofxie, any plans to fix this soon?

**Comment by gagankohli2000** [comment] 2020-02-23 09:21
@darrenj - I'm using VA with ITSM and Calendar skill. My issue is that they both worked initially but I'm continuously having issue with token.
On teams channel I'm getting error for Calendar skill "The Sign In code was not found or expired. Please try asking the bot to sign in again." While ITSM is working fine.

On Web chat (Our Website) i get error "Your log in failed. Let’s try this again." for ITSM but Calendar skill is working fine.
Both are working fine on Azure web chat and Emulator.

**Comment by xieofxie** [comment] 2020-02-24 06:28
hi @csnarain, the patch will be slow as we are in a release process. For your calendar skill Teams login issue, you could use this https://github.com/microsoft/botframework-solutions/blob/master/skills/csharp/experimental/itsmskill/Bots/DefaultActivityHandler.cs to replace this https://github.com/microsoft/botframework-solutions/blob/master/skills/csharp/calendarskill/Bots/DefaultActivityHandler.cs.

@darrenj The TeamsActivityHandler are only applied in four skills. This would be fixed after the move.

**Comment by csnarain** [comment] 2020-02-24 13:59
hi @xieofxie - Thanks. That helped to get this integrated to Teams. However, the adaptive cards are not rendering properly. If you look at it closely, the controls are missing and colors are not appearing appropriately. 

![image](https://user-images.githubusercontent.com/9998645/75158377-f565d500-573b-11ea-98ec-30a03119f9c9.png)

**Comment by xieofxie** [comment] 2020-02-25 02:29
hi @csnarain These are implemented when Teams didn't support adaptive card 1.2 and they are 1.0 style cards. Now Teams supports 1.2 and they will be fixed (tracked in #3106).

**Comment by csnarain** [comment] 2020-02-25 05:21
@xieofxie - What I'm confused with is, the same cards are rendering fine with bot emulator v4. The issue happens only with Teams. While you work on the fix, where can I find documentation to fix this for Teams? I need this at the earliest for one of our customer demos.

**Comment by xieofxie** [comment] 2020-02-25 07:20
@csnarain Sadly, it turns out that I am too optimistic.. They still don't support svg now.

Yet I figured out a workaround for you: 
We detect Teams and determine the card we use here https://github.com/microsoft/botframework-solutions/blob/efe1a4ddaf5d95e7db3069610bfd501b58726b0b/skills/csharp/calendarskill/Dialogs/CalendarSkillDialogBase.cs#L2393

So basically, you could
* Copy content of *Card.Text to *V1.Text in https://github.com/microsoft/botframework-solutions/blob/master/skills/csharp/calendarskill/Responses/Card/Card.lg
* Replace svg string with png string with steps like
    - paste svg string in chrome and download svg file
    - https://svgtopng.com/
    - https://onlinepngtools.com/convert-png-to-base64

An example: https://github.com/microsoft/botframework-solutions/commit/95b32f9bcbfa277f8f857cf6f6eb1fd4ecb0c8ea

Result (it is blur if you didn't choose png size wisely..):
![image](https://user-images.githubusercontent.com/2876650/75223811-3adcdd80-57e2-11ea-878c-09c34820611f.png)

**Comment by csnarain** [comment] 2020-02-25 15:45
@xieofxie  - Thanks again. That did help but for one issue. The two arrows on the card for navigation are not working. Nothing happens when we try to click on them. This didn't work in emulator as well. Is this a known behavior?

**Comment by xieofxie** [comment] 2020-02-26 01:58
@csnarain Yes, it is expected behavior.
@KayMKM Add this to backlog ? (But I didn't find this in new design..)

**Comment by darrenj** [comment] 2020-02-28 13:55
The arrows were an indicator of there being more items so you could go next/preview. They are removed from the latest adaptive card designs.

**Closed as completed by darrenj** 2020-02-28 13:55 UTC
Labels: Type: Bug, customer-reported, customer-replied-to, Bot Services
