### ISSUE TITLE
[Virtual Assistant Template] Multi-language deployment creates QnA KBs incorrectly.

### ISSUE THREAD

**Issue by ypom** [microsoft/botframework-solutions#1555] opened 2019-06-14 16:08 UTC
## Project

**Name**: Virtual Assistant

**Language**: C#

## Description
Multi-language deployment using *deploy.ps1* script of VA template creates QnA KBs incorrectly.  All Azure search indexes created are using the same 'English' analyzer for all languages. This affects quality of QnA maker responses.

Per my understanding this is because deployment script *deploy_cognitive_models.ps1* adds
knowledge bases for different languages to the same QnA service. But according to the [article](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/language-knowledge-base) : *"Each QnA Maker service should be reserved for a single language. The first knowledge base created targeting a particular QnA Maker service sets the language of that service"*

I guess deployment scripts and ARM template should be updated to create QnA service per language.

## To Reproduce
run: deploy.ps1 -languages "en-us,de-de" ....

## Screenshots
![image](https://user-images.githubusercontent.com/29462281/59522526-8c08a380-8ed7-11e9-919c-3df8f82e0643.png)

**Comment by lauren-mills** [comment] 2019-06-14 18:24
We need to do some more investigation on this, because that would quickly exhaust the Azure Search quota for a subscription and the cost would be very high as well. If an assistant was deployed in say, 3 languages, that would mean 3 search services, three app services, etc.

**Comment by ypom** [comment] 2019-06-18 09:44
Yes, having 3 services (cognitive, app, search) per language is not cost effective solution. May be this issue should be forwarded to QnA maker team for consideration.

**Comment by mutanttech** [comment] 2019-06-19 07:50
> Yes, having 3 services (cognitive, app, search) per language is not cost effective solution. May be this issue should be forwarded to QnA maker team for consideration.

This felt really unnecessary and absurd that for supporting different language in QnA Maker it would require a whole different QnA Service (which means its dependent service). 
Azure Search is powerful service and costly as well, so definitely above does not makes sense.
I had to support Danish Language in KB and as state above it Analyzer is set to English only. So far I haven't seen much issues, but we intend to support Chinese as well. Hope QnA Maker team thinks about this seriously.

**Comment by lauren-mills** [comment] 2019-06-19 10:25
We can work on raising this issue with the QnA team. In the meantime, it might be good to raise an issue on the referenced doc page for tracking.

**Comment by lauren-mills** [comment] 2019-06-19 12:09
Confirmed that user voice is the team's preferred way of communication around feedback and requests.

Closing this issue here, but it can be tracked/voted on at this user voice submission: https://cognitive.uservoice.com/forums/578689-qna-maker-api/suggestions/37945525-support-for-multiple-languages-per-qna-service

**Closed as completed by lauren-mills** 2019-06-19 12:09 UTC
