### ISSUE TITLE
msbot update

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#322] opened 2018-11-20 00:17 UTC
**Is your feature request related to a problem? Please describe.**
msbot clone can not run twice, it ends up duplicating resources and also fails when attempting to create cosmosDB.
Right now, the only alternative is to delete, recreate and reconfigure the entire resource group.

**Describe the solution you'd like**
It is time consuming to assign keys and tune pricing tiers for deployed assistants, we may also lose data that we want to keep.
It will be good to have an msbot update option that:
* skips the creation of resources if they are already there (app plan, bot registration, cosmos, storage, etc.)
* updates resources that need to be updated: .bot file, LUIS model and QnAMaker.

**Comment by lauren-mills** [comment] 2018-11-20 00:59
This is in progress!

**Comment by lauren-mills** [comment] 2018-11-20 01:01
Duplicate of #231

**Closed as completed** 2018-11-27 15:55 UTC
