### ISSUE TITLE
Virtual Assistant not working in "Test in Web Chat" or in Direct Line Speech

### ISSUE THREAD

**Issue by pulakkumar599** [microsoft/botframework-solutions#3592] opened 2020-07-28 14:15 UTC
Hi,

I tried to deploy the virtual assistant created from the "Virtual Assistant Template" from the visual studio 2019. The deployment was done successfully using azure cli in powershell scripts (deploy.ps1). It is working successfully locally in a Bot Emulator but it is not working in "Test in Web Chat" inside azure portal and also if we connect Direct Line Speech Channel to the bot, it is not working using the Direct Line Speech Client.

Steps followed from this tutorial:
[https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/csharp/2-download-and-install/](url)

Please suggest any fix asap.

Thanks,
Pulak Kumar Swain

**Comment by pavolum** [comment] 2020-07-28 22:33
Hey @pulakkumar599  thanks for reaching out.

Do you happen to have the output of deploy.ps1 handy? That script should not only provision all your resources but also publish your bot to its provisioned resources. I just ran through this flow and I am able to test in web chat in the azure portal. My deploy.ps1 output looks like this.
```
...
> Publishing to Azure ...Done.
+ Summary of the deployed resources:
    - Resource Group: DeleteMeAssistant
    - Bot Web App: DeleteMeAssistant-uvyd7gp
    - Microsoft App Id: XXXXX-XXXX-XXXX-XXXXXXXX
    - Microsoft App Password: XXXXXXXX
> Deployment complete.
Test your deployed bot on the bot framework emulator with the following link (copy and paste link into windows -> run to open the emulator with your deployed bot configured)
bfemulator://livechat.open?botUrl=
...
```

There is a chance that your deployment script had an error on the publish step. When you go to your provisioned bot in the azure portal and click 'test in web chat' what happens? Do you get an error message, does the bot not connect at all or not answer any incoming queries? 

Since your bot works locally, I would suggest republishing your VA and trying again to ensure your local VA is published to its app service. You can either publish your VA through Visual Studio (Right click the project, select 'publish' and choose the web app bot service provisioned for you when you ran delpoy.ps1) or run our publish script [outlined here](https://microsoft.github.io/botframework-solutions/virtual-assistant/handbook/deployment-scripts).

Let me know how it goes. Hopefully a simple publish will be the fix.

**Comment by pulakkumar599** [comment] 2020-07-29 11:31
Hi @pavolum 

The deploy.ps1 output looks the same as you have shared and we did not get any error while deploying the bot.
But as you have mentioned we do not any any error message when we try to "test in web chat", instead the " bot does not connect at all or not answer any incoming queries".

I also tried to "testin web chat" publishing 2 times even after deploying successfully using the publish.ps1 script.
Please find below the images.


![image](https://user-images.githubusercontent.com/25700580/88807454-5d2eb900-d1cf-11ea-8ba9-57922e3ed439.png)

![image](https://user-images.githubusercontent.com/25700580/88807566-83545900-d1cf-11ea-8e8d-f67d3d961aa4.png)


Thanks,
Pulak Kumar Swain

**Comment by pavolum** [comment] 2020-07-30 18:37
Hmmm I am not able to repro this. Can you try using emulator and configuring it to hit your published bot as opposed to the bot you have running locally?

So in emulator when you open a new bot, have the Bot URL hit your published bot url (from the above screenshot it looks like the appservice name would be pullbot292-ouh645l.azurewebsites.net/api/messages) and fill out appID and password
![image](https://user-images.githubusercontent.com/22845013/88960740-cf97ab80-d258-11ea-8540-32aa1d0e7074.png)

Try testing your published bot in this environment. Hopefully the log in the bottom right of the emulator UI gives you some meaningful error we can work with.

**Comment by pulakkumar599** [comment] 2020-07-31 06:40
hi @pavolum,

I tried the above steps by giving the Bot endpoint in the bot emulator but still I am not getting any response.
![image](https://user-images.githubusercontent.com/25700580/89007662-cb39c400-d326-11ea-9329-e097e61dd894.png)

Regards,
Pulak Kumar Swain

**Comment by pulakkumar599** [comment] 2020-08-04 04:56
hi @pavolum 

Any update on this issue.

Thanks,
Pulak Kumar Swain

**Comment by pavolum** [comment] 2020-08-04 17:16
Hey @pulakkumar599 Im afraid I dont have an update for you. I have run through this flow a few times and am not able to reproduce the issue. I was hoping to get some meaningful error from your emulator test but the bot seems to connect but is not reacting to the conversation update activity as expected. Do you get any error when you send a message to the published bot through emulator?

Also do you have a different appsettings.json or cognitvemodels.json for development and for production if so a discrepancy here may result in the published bot not working while the local bot does. When you test your bot locally and it works are you using a debug build? Perhaps you can test it locally with a production build as that would accurately mirror the published environment. Can you think of anything that may be different between the published bot and the local one? It seems to me that the publish and deploy tooling worked as expected.

Also I see an ngrok error in the emulator screenshot. Do you have Ngrok installed and configured locally?

I am reaching out to the broader team to get any potential insights. Without being able to repro it or have a meaningful error message there is not much I can do.

**Comment by pavolum** [comment] 2020-08-04 18:45
Couple other tips:
- Please validate the appsettings and cognitivemodels json files on your published endpoint using [Kudu](https://4sysops.com/archives/use-kudu-to-manage-azure-web-apps/). The linked doc will show you how it works. Essentially go to pullbot292-ouh645l.scm.azurewebsites.net this will put you in your Kudu portal, click debug console -> CMD and then navigate to `site/wwwroot/`. In this directory you will see your appsetting.json and cognitiveModels.json files associated with your published bot. Please validate that they are filled out correctly. 

- Check for errors in your appInsights log for any exceptions. An appInisghts instance should have been deployed alongside your bot in the same resource gorup. Go to the appinsights resource, go to logs and search for exceptions. Please post any exception messages here. 

My hope is that some of these troubleshooting steps will get us an error message we can work with.

**Comment by peterinnesmsft** [comment] 2020-08-17 22:53
Since there has been no update in approximately two weeks, closing this issue out. @pulakkumar599 if you believe this to be a product issue that we can still assist with, feel free to reactivate and we can take a look.

**Closed as completed by peterinnesmsft** 2020-08-17 22:53 UTC
Labels: Type: Bug, customer-reported, customer-replied-to, Bot Services
