### ISSUE TITLE
Works in Emulator but not in Test Web Chat or MS Teams

### ISSUE THREAD

**Issue by Robotbae** [microsoft/botframework-solutions#2331] opened 2019-09-09 10:54 UTC
#### What project is affected?
BotSolutions Sample Assistant Template

#### What language is this in?
Typescript

#### What happens?
I am not sure what the reason is where test web chat does not load and Bot does not respond on MS Teams but works perfectly fine in Bot Emulator. 
![image](https://user-images.githubusercontent.com/50206076/64525227-4271fe00-d2f8-11e9-8305-b8b53494014f.png)
![image](https://user-images.githubusercontent.com/50206076/64525308-6f261580-d2f8-11e9-9055-35fce14d4649.png)
![image](https://user-images.githubusercontent.com/50206076/64525264-56b5fb00-d2f8-11e9-9a24-3231952c4609.png)

#### What were you expecting to happen?
Hoping for the bot to respond

#### Can you share any logs, error output, etc.?
No errors - application insights off, tried local tunnelling but gave 500 request error so switched back endpoint to resourcegroup.azuresomethingsomething.net

**Comment by Robotbae** [comment] 2019-09-09 11:01
Also checked that web socket has been enabled

**Comment by xieofxie** [comment] 2019-09-09 11:11
Do you set up Teams channel in web app bot's settings?

**Comment by Robotbae** [comment] 2019-09-09 11:51
Ye I did - 
Is the below what you mean?

![image](https://user-images.githubusercontent.com/50206076/64528482-8537d400-d300-11e9-8004-c1ed20887263.png)

![image](https://user-images.githubusercontent.com/50206076/64528456-77824e80-d300-11e9-9d6c-d4896c1219d0.png)

**Comment by xieofxie** [comment] 2019-09-10 02:47
OK, I would suggest to check the following:

- In Web App Bot's Settings, does messaging endpoint contain a public available url? It could be a deployed one like some azure or a ngrok.
- Test the url in emulator to see if it works
- Click on Test in Web Chat to chat online/Microsoft Teams in Channels to open in Teams. They should work after the above

**Comment by urdurgaprasad** [comment] 2019-09-10 17:02
We are also observing the same issue, bot working fine in emulator and other channels but throwing "There was an error sending this message to your bot: HTTP status code GatewayTimeout " error in teams. Here we have parent and child bot model, i.e. master bot with teams channel and child bot as direct line channel. And we are invoking child bots from master bot based on intent. Master bot is responding in teams, but child bots are not responding. 

Another observation, issue is not reproducible with users who are is using teams bot in NALA region. Issue for users located in APAC and EMEA locations.

**Comment by mdrichardson** [comment] 2019-09-10 18:21
Investigating. As "Test in WebChat" isn't even working, my guess is that the bot didn't deploy properly or isn't running for some reason. I'll see if I can repro and track this down.

@urdurgaprasad 	Is your bot also a Typescript bot? Does yours work in WebChat? It sounds like yours may be a separate issue. If so, please [open a separate issue](https://github.com/microsoft/botframework-solutions/issues/new?assignees=&labels=Needs+Triage%2C+Type%3A+Bug&template=bug_report.md&title=) so that we can track these both better.

**Comment by urdurgaprasad** [comment] 2019-09-10 18:58
@mdrichardson It is Node JS based child bot, works well in web-chat and emulator. Please confirm if you want me to still raise a separate issue.

**Comment by mdrichardson** [comment] 2019-09-10 19:02
As yours works in WebChat (which this user's does not) while yours still works occasionally in Teams (this user's does not at all), please open a separate issue. Off-hand, yours might be a [TrustServiceUrl issue](https://github.com/Microsoft/BotBuilder/issues?q=label%3A%22Trust+Service+URL%22+is%3Aclosed), which could possibly be fixed with something like:

```js
MicrosoftAppCredentials.TrustServiceUrl(context.activity.serviceUrl);
```

But yes, please open a separate issue for this.

**Comment by Robotbae** [comment] 2019-09-10 21:46
Hello - ok so what I've tried to do is to test the deploy.ps1 theory. Think you're onto something. 

- I downloaded https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant
- changed the name to 'The Assistant' in package.json and package-lock.json 
- I then opened pwsh 6, changed directory to project folder, ran az login and then ran deploy.ps1 
- all resources were deployed accordingly and could see web app bot created. So before running publish.ps1 (I dont believe you need to yet) decided to test on web chat....and : 

 
![image](https://user-images.githubusercontent.com/50206076/64652843-b73e5880-d41c-11e9-81dc-305da788ed09.png)


So just isolating the deploy.ps1 script here

**Comment by mdrichardson** [comment] 2019-09-10 21:49
@Robotbae Thanks for the report! I'm still looking into this. Although the deployment was successful, it looks like the bot may have trouble running itself while deployed.

**Comment by mdrichardson** [comment] 2019-09-10 22:28
@Robotbae Can you go to `https://<yourBot>.scm.azurewebsites.net/dev/wwwroot/` and see what files are listed there? It should look mostly like your local bot directory.

**Comment by Robotbae** [comment] 2019-09-11 06:01
@mdrichardson This is what happened:  
![image](https://user-images.githubusercontent.com/50206076/64672017-2a1df280-d462-11e9-9f54-cb3600704d31.png)


Also ran the message endpoint for safe measure 

![image](https://user-images.githubusercontent.com/50206076/64671914-dad7c200-d461-11e9-8ff7-76d470cc5888.png)

Happened to the first bot as well the same message popped up 


***** Edit ****** 

Ok fast forward 40 mins later, ran publish.ps1 (the one from last week not the latest one with npm run build and install). The files now appear in the App Service Editor 

![image](https://user-images.githubusercontent.com/50206076/64673922-630c9600-d467-11e9-9099-6588bb53b554.png)
 
Test web chat still no response

**Comment by mdrichardson** [comment] 2019-09-11 21:19
@Robotbae

Can you please go to `https://<yourBot>.scm.azurewebsites.net/dev/wwwroot/:vs.console`, then click Run:

![image](https://user-images.githubusercontent.com/40401643/64736252-147aee00-d49f-11e9-9839-c2448c7098b3.png)

...then Test in WebChat from a different tab/window, and then watch the `output` window for messages. Please copy/paste any errors.

---

Also, it looks like you may need to `npm run build` prior to publishing, so that it populates `/lib/appsettings.json`

After doing this, mine worked. Keep in mind, it will throw some build errors on your local machine, but still work when `publish`ed.

---

Also, keep in mind that Virtual Assistant is still in Preview. I believe the development priorities are something like `Dotnet > TypeScript > Docs`, so be prepared for other stuff to need troubleshooting.

**Comment by Robotbae** [comment] 2019-09-13 09:23
hey! Sorry for taking 2 days wifi hasn't been great here where I am 

Instead of continuing on with the-assistant, started from scratch again with a new bot. Pressed run (note that appsettings appear), I think this is the furthest I've been to getting in right

![image](https://user-images.githubusercontent.com/50206076/64851912-42cc0b00-d610-11e9-877e-8a4caf869ac0.png)

![image](https://user-images.githubusercontent.com/50206076/64851958-5a0af880-d610-11e9-9241-d69ca1dcd235.png)



****** lunch time break quick update*************

Reran everything from the latest update with tslint , npm run build then publish.ps1. Still same error on new bot

**Comment by mdrichardson** [comment] 2019-09-13 16:29
@Robotbae Please press Run and then watch the console output in that tab while using Test in WebChat. It should present some error messages that will clue us in to how to solve this.

**Comment by mdrichardson** [comment] 2019-09-18 15:48
@Robotbae Any luck? This issue needs to stay active to stay open.

**Comment by mdrichardson** [comment] 2019-09-20 14:53
Closing due to lack of activity.

**Closed as completed by mdrichardson** 2019-09-20 14:53 UTC
Labels: Type: Bug, Support, customer-reported, customer-replied-to, Bot Services

**Comment by Robotbae** [comment] 2019-11-28 14:38
Hi @mdrichardson  

I never thanked you for your help on this. I haven't tested out the new deployment I ultimately resorted to created an app on Azure Portal and changing the code on Online App Editor. 

Thank you again for your guidance on this

**Comment by mdrichardson** [comment] 2019-12-02 15:55
@Robotbae No problem. Glad you got it working!

**Comment by danorama-dev-dh** [comment] 2020-05-04 10:17
Hi, same problem here. My Bot is working in the emulator but neither in Webchat nor Teams.

> Can you please go to `https://<yourBot>.scm.azurewebsites.net/dev/wwwroot/:vs.console`, then click Run

When I click Run I get the following:
`
[info] Output will appear here from the running application at http://<mybot>.azurewebsites.net
[info] Logging has been enabled for your application
[info] The logging level is 'Information'. To change this, go to the 'Diagnostics Logs' page in your app settings and change the 'Application Logging' setting.

[info] Restarting server...
[warn] The node server startup file 'server.js' could not be found. Please create it or change the configuration in D:\home\site\wwwroot\web.config
[info] Click on http://<mybot>.azurewebsites.net to open your site
`
