### ISSUE TITLE
Error while running connect/update using botskills CLI

### ISSUE THREAD

**Issue by manish-95** [microsoft/botframework-solutions#3057] opened 2020-02-14 13:42 UTC
#### What happens?
When I try to connect/update a skill to the main VA Bot using botskills connect/update, I get an error which prevents me from proceeding further.

#### What are the steps to reproduce this issue?
1. Use bf luis:version:export to generate .json file for the Skill Bot.
2. Use bf luis:convert to update the .lu file with new changes for the same Skill Bot.
3. Run botskills update/connect to update the dispatch of the VA bot.
 
#### What were you expecting to happen?
The .dispatch and .luis files of the VA Bot to be updated with details of the Skill template.

#### Can you share any logs, error output, etc.?
`Error: The execution of the ludown command failed with the following error:
[ERROR] line 989:0 - line 989:1: syntax error: invalid input '@' detected. Expecting one of this - end of file, model description, new line, QnA definition, Intent definition, Entity definition, Import statement
[ERROR] line 993:0 - line 993:1: syntax error: invalid input '@' detected. Expecting one of this - end of file, model description, new line, QnA definition, Intent definition, Entity definition, Import statement
Stopping further processing.`

**Comment by lauren-mills** [comment] 2020-02-14 19:35
Hi @manish-95, what version of the botskills tool (run `botskills -v`) are you using?

**Comment by manish-95** [comment] 2020-02-16 17:28
Hi @lauren-mills , I am using version 1.0.13

**Comment by manish-95** [comment] 2020-02-19 04:42
@lauren-mills  Any updates on this? I am still facing this issue.

**Comment by lzc850612** [comment] 2020-02-19 04:50
what is the version of the VA Template that you created your VA with? is it 4.7.0.2 that's released in our latest 0.8 beta release?

**Comment by manish-95** [comment] 2020-02-19 05:38
@lzc850612 Yes, I am using the same version that was released as part of the 0.8 Beta Release.

**Comment by darrenj** [comment] 2020-02-19 10:39
Looks like there might be an issue with the format of the LU file it's trying to process, are you able to share the LU file that you updated?

**Comment by manish-95** [comment] 2020-02-20 06:10
@darrenj Here is the file.
[MBVEmceeSkill_Dev.zip](https://github.com/microsoft/botframework-solutions/files/4229077/MBVEmceeSkill_Dev.zip)

**Comment by manish-95** [comment] 2020-02-22 12:50
@darrenj Any updates on this?

**Comment by DiegoCardozo94** [comment] 2020-02-27 18:34
Hi @manish-95, we **successfully** reproduced the issue which is related to some wrong characters identified by ludown tool during the connect execution of botskills.

![image](https://user-images.githubusercontent.com/42946572/75474823-6e507100-5976-11ea-9bd6-f9133d36e86a.png)

As a **workaround**, can you try creating the LU file using `ludown`?
Please, follow these steps having the `.json` file for the Skill Bot:
1. Install [ludown](https://www.npmjs.com/package/ludown) tool
> npm install -g ludown
2. Execute `ludown refresh --in <JSON_FILE>`
3. Check that the LU file was created correctly
4. Execute botskills connect using the created LU file

We noticed that the LU file created by [botframework-cli](https://github.com/microsoft/botframework-cli) executing `bf luis:convert` is not supported by botskills as it differs with the format needed by ludown.

_Comparison between the LU file format created using ludown and botframework-cli_
![image](https://user-images.githubusercontent.com/42946572/75474843-77d9d900-5976-11ea-8a33-040351b9e5fa.png)


Finally, we will update the [Known Issues](https://microsoft.github.io/botframework-solutions/help/known-issues/) documentation adding this scenario.

**Comment by darrenj** [comment] 2020-03-02 17:38
@manish-95  Did that help?

**Comment by darrenj** [comment] 2020-03-06 08:42
Please re-open if you still have issues.

**Closed as completed by darrenj** 2020-03-06 08:42 UTC
Labels: Type: Bug, customer-reported, customer-replied-to, Bot Services

**Comment by IanIDG** [comment] 2020-05-02 14:22
Even after running workaround using ludown, botskills will not parse .lu file. Error seems to be with entities of List type, where there is an apostrophe in the main definition,  e.g. ... 
> # List entities
$coffeeshop:Starbuck's=

Whereas 
$coffeeshop:Starbucks= 
- Starbuck's
works ok

**Comment by darrenj** [comment] 2020-05-02 14:35
Can you update to latest botskills? Ludown is replaced with bf CLI

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by IanIDG** [comment] 2020-05-02 14:58
I am already using latest 1.0.14. Workaround easy enough, just edited the .lu to ensure no ' in the main entity definitions. I also have bf, but only needed ludown for this main issue (incompatible .lu formats between what gets created from the LUIS portal by update_cognitive_models.ps1 -RemoteToLocal and what botskills expects). I guess this tool chain is still maturing ... looking forward to next iteration.
