### ISSUE TITLE
Azure Devops Pipeline failing on Nuget restore with latest bot-solutions package 1.1.0

### ISSUE THREAD

**Issue by tomSauret847** [microsoft/botframework-solutions#3833] opened 2021-07-01 15:40 UTC
#### What happens?
when using the sample [here](https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/assistants/virtual-assistant) the build pipeline fails with the following error
##[error]The nuget command failed with exit code(1) and error(F:\agents\_work\_tool\dncs\2.2.100\x64\sdk\2.2.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.1. 

#### What are the steps to reproduce this issue?
build new template using latest version
use pipeline example that is included in the template
push project to Azure Devops and let the build pipeline run

#### What were you expecting to happen?
The build to succeed and the project is built
#### Can you share any logs, error output, etc.?
see above error

**Comment by axelsrz** [comment] 2021-07-06 18:21
@lauren-mills could you please look into this issue and provide some feedback? thanks

**Comment by lauren-mills** [comment] 2021-07-06 18:49
@Batta32 - it seems like the pipeline yaml may need to be updated to support the latest code. Can you take a look?

**Comment by Batta32** [comment] 2021-07-06 18:54
Sure @lauren-mills! We will take a look at this issue as soon as possible.

Thanks @tomSauret847 for reporting this issue, as soon as we have any update, we will back to you here 😊.

**Comment by Batta32** [comment] 2021-07-08 22:32
Hi @tomSauret847, we have planned to work on this issue in the next week.

We will let you know any update 😊.

**Comment by matiasroldan6** [comment] 2021-07-12 19:41
Hi @tomSauret847, we were able to reproduce this. Our setup was:

- The [Virtual Assistant](https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/assistants/virtual-assistant) located in the repository
- An Azure Pipeline created with the [VirtualAssistantSample.yml](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Pipeline/VirtualAssistantSample.yml) located in the repository folder

We got the error saying the .NET SDK does not support targeting .NET Core 3.1, most likely because the .NET Core version specified in the YAML file is [2.2.100](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Pipeline/VirtualAssistantSample.yml#L22) while the current Virtual Assistant project is on .NET Core [3.1](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj#L4).
We will work on finding the best approach for updating the YAML.
![image](https://user-images.githubusercontent.com/20074735/125346215-d9160880-e32f-11eb-9736-5e3f16d75897.png)

**Comment by hcyang** [comment] 2021-07-15 18:23
Hi @matiasroldan6 and @Batta32, any update to a solution?

**Comment by matiasroldan6** [comment] 2021-07-16 16:03
Hi @tomSauret847, @hcyang. Sorry about the delay, we found some things out of date in the Virtual Assistant's YAML which we fixed in PR #3835.

You can take this PR -or wait until it is merged- and see if it fixes the issue you have. Let us know of any further issues.

**Comment by tomSauret847** [comment] 2021-07-19 12:05
Thank you @matiasroldan6 for looking into this. I took the PR and updated my project and was able to get the project to build. It is now working as expected.

**Comment by hcyang** [comment] 2021-07-19 15:17
Thanks @tomSauret847 for raising the issue and @matiasroldan6 for providing a solution. Closing the issue now.

**Closed as completed by hcyang** 2021-07-19 15:17 UTC
Labels: Type: Bug, Needs Triage, customer-reported, customer-replied-to, Bot Services, ExemptFromDailyDRIReport, Team: Kobuk
