### ISSUE TITLE
Skill A dialog doesn't end and hence doesn't go to "Skill B" or back to "VA" after upgrading to "4.7.0" 

### ISSUE THREAD

**Issue by Edwardfelix08** [microsoft/botframework-solutions#2919] opened 2020-01-27 10:10 UTC
#### What project is affected?
VA and Skill 

#### What language is this in?
Type Script

#### What happens?
The context inside the skill doesn't get cleared inside a skill and hence the control remains inside the skill and doesn't come back to VA in an VA-Skill Architect Bot.
This results into, the **VA** is able to identify the right **Skill intent** but it is not able to call the **Skills's** or the **dialogs in the VA**.

#### What are the steps to reproduce this issue?
Deploy the sample
VA using the  **"botbuilder": "^4.7.0"** or the latest versions
Skill using  "botbuilder-skills": "^4.4.9", using the typescript bot sdk.

#### What were you expecting to happen?
When the **Skill A** dialogs ends the bot must be able to end the conversation and clear the context to call the next requested dialog of **VA** or the other **Skill B'.

**Comment by VictorGrycuk** [comment] 2020-01-29 13:25
Hi @Edwardfelix08!

We will look into this and get back at you.

**Comment by VictorGrycuk** [comment] 2020-01-30 21:09
Hi @Edwardfelix08,

We were able to reproduce your scenario by using the BotBuilder [Skill Sample](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-skill) and [Sample Assistant](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant) in the `master` branch. We also tried the same steps using the `next` branch and the issue was not found.

To confirm whether the control was being given back to the assistant or not after the execution of the skill, we added a second sample skill and tried to call it after the execution of the first skill.

1. Deploy a [Sample Virtual Assistant](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant)
2. Deploy a [Sample Skill](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-skill)
3. Create a [Sample Skill](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-skill), but make sure to use different utterances, questions, and answers to difference it from the first skills, such as:
   - [SampleResponses.json](https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/responses/sample/:/SampleResponses)
   - [sampleSkill.lu](https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/typescript/samples/sample-skill/deployment/:/LU/en-us/sampleSkill.lu)
4. After the Virtual Assistant and Skills are deployed, start them and execute the `run sample dialog` utterance of the first skill.
5. After completing the waterfall dialog, the control will not be given back to the Virtual Assistant. Even sending the utterance for the second skill will not work.

As can be seen in the image below, we interacted with the first skill and then tried to execute the second one (with the utterance `alternative`) but it was not successful.
![image](https://user-images.githubusercontent.com/39467613/73490487-6c04f200-438b-11ea-9b56-96a7f496d6b8.png)

Also, the [complete event](https://github.com/microsoft/botframework-solutions/blob/next/templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts#L254) of the assistant was not reached.

We tried the same steps using the `next` branch, and on this branch the control was indeed given back to the Virtual Assistant:
![image](https://user-images.githubusercontent.com/39467613/73490515-77581d80-438b-11ea-9ed6-15c2590aa932.png)
As seen in the image above, we interacted with the first Sample Skill, and after its completion we run the second Sample Skill (again, denoted with the utterance `alternative`), and it was executed successfully.

**Note:** To use the `next` branch, it is necessary to build the [BotBuilder Solutions](https://github.com/microsoft/botframework-solutions/tree/next/sdk/typescript/libraries/botbuilder-solutions) and [BotBuilder Skills](https://github.com/microsoft/botframework-solutions/tree/next/sdk/typescript/libraries/botbuilder-skills) locally, and update the `package.json` of both the Virtual Assistant and Skill to use the local `.tgz` files, as they are not released yet.

Could you please confirm us that this is the behavior that you encountered?

**Comment by Edwardfelix08** [comment] 2020-01-31 06:34
Hi @VictorGrycuk, 
 Thanks for replying to us.

**Could you please confirm us that this is the behavior that you encountered?**
**Yes** it the same behavior which we encountered, and we have not tried to use the next branch.

When can we expect to this issue been resolved.

Thanks,
Edward

**Comment by VictorGrycuk** [comment] 2020-02-05 15:43
Hi @Edwardfelix08,
The `next` branch has been merged with the `master` branch.

Please test again with the newly implemented changes and let us know if the issue persist

**Comment by marawanshalaby** [comment] 2020-02-10 07:25
hey @VictorGrycuk , does the 4.7.2 release include this fix already or should we still build from source?

**Comment by VictorGrycuk** [comment] 2020-02-10 13:25
Hi @marawanshalaby,

The problem has been fixed on the master branch of BotBuilder Solutions (not in botbuilder@4.7.2), you will have to build from source.

**Comment by marawanshalaby** [comment] 2020-02-10 13:31
hey @VictorGrycuk , was the fix related to the change from handoff -> EndOfConversation? Because that's the only change we had to do on our skill side (without building anything from source) and it works now:

![image](https://user-images.githubusercontent.com/45569036/74153889-d16da400-4c11-11ea-877c-30a937a92853.png)

The "Hello" message is a message generated by the skill, then we send the EndOfConversation activity from the skill which terminates the skill on the VA side and then we are back interacting directly with the VA

**Comment by Edwardfelix08** [comment] 2020-02-11 11:31
Hi @VictorGrycuk, When can we expect this to be released because we are highly dependent on this update.
We will try it out with the master branch and see if it's working fine.

Thanks,
Edward

**Comment by VictorGrycuk** [comment] 2020-02-11 18:05
Hi @marawanshalaby,

This was solved with the modifications that were introduced with the merge of the `next` branch, specifically on the PR #2842 Parity to release 0.6Beta.

This PR replaced `EndOfConversation` for `Handoff`:
![image](https://user-images.githubusercontent.com/39467613/74264481-74d8ba80-4cdf-11ea-947e-04f14a726db3.png)

Prior to this PR, the [Skill's mainDialog](https://github.com/microsoft/botframework-solutions/blob/6a5caa666274d0fe58e1ca0e3fd5ab0a0cadcb57/templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/dialogs/mainDialog.ts#L128) was sending a `Handoff`, but this caused the Virtual Assistant to throw an exception to unknown activity type:
![image](https://user-images.githubusercontent.com/39467613/74264532-8d48d500-4cdf-11ea-81f0-4210b8d64830.png)

**Comment by marawanshalaby** [comment] 2020-02-13 09:42
hi @VictorGrycuk understood, thank you very much

**Closed as completed** 2020-02-19 10:49 UTC
Labels: Type: Bug, customer-reported, Bot Services
