### ISSUE TITLE
Creating Visual Studio 2019 Project using the Virtual Assistant Template fails

### ISSUE THREAD

**Issue by MHeadroom** [microsoft/botframework-solutions#3671] opened 2020-09-30 09:16 UTC
I was following the tutorial in order to create a Virtual Assistant. I downloaded and installed all necessary resources as described here:

https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/csharp/2-download-and-install/

In the nextstep one is asked here

https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/csharp/3-create-project/

to create a Virtual Assistant project in Visual Studio using the Virtual Assistant template. The creation fails with an error message that the project file cannot be migrated.

![image](https://user-images.githubusercontent.com/72129017/94666738-23cd1380-030e-11eb-84c4-ad4a40e73a5e.png)

A similar issue is described here:

https://github.com/microsoft/botframework-solutions/issues/2635

Hence I installed the additional Microsoft.NETCore.App as described there - to no avail...

As it seemed to be a problem connected with Visual Studio I opened then a thread in the Visual Studio Community, see:

https://developercommunity.visualstudio.com/content/problem/1194245/cannot-create-virtual-assistant-project.html

Jeff Kelly from Microsoft analysed the error logs and said that VS cannot find the .NET Core SDK installed on my machine.

![image](https://user-images.githubusercontent.com/72129017/94665738-d13f2780-030c-11eb-9ab1-5e123d0ce45f.png)

But the resources are there, see this output from powershell commands "dotnet --info" and "node -v":

![image](https://user-images.githubusercontent.com/72129017/94666162-64785d00-030d-11eb-9c29-ecfb4595e528.png)

Jeff assumes that there is something wrong with the template and recommended to open a new issue here...

Thanks for your help!

**Comment by Batta32** [comment] 2020-09-30 13:35
Thanks @MHeadroom for reporting this issue. In order to narrow your environment, we came up with some **questions**:
1. Which version of the VSIX have you installed?
1. Have you checked this [comment](https://github.com/microsoft/botframework-solutions/issues/2635#issuecomment-555691295) of the similar issue you attached #2635?
1. Have you checked if this issue happens using another version of VS?

We will be reviewing this trying to reproduce the environment and the issue, also reviewing the [issue](https://developercommunity.visualstudio.com/content/problem/1194245/cannot-create-virtual-assistant-project.html) you raised, as soon as we have any update we will back to you 😊.

**Comment by MHeadroom** [comment] 2020-09-30 15:50
Hi there, thanks for the quick reply. In answer to your questions:

1. Here's all information on my Visual Studio version and installed extensions (copied from VS menu / Help / Info about Microsoft Visual Studio):

Microsoft Visual Studio Community 2019
Version 16.7.5
VisualStudio.16.Release/16.7.5+30523.141
Microsoft .NET Framework
Version 4.8.03752

Installierte Version: Community

Visual C++ 2019   00435-60000-00000-AA067
Microsoft Visual C++ 2019

C#-Tools   3.7.0-6.20459.4+7ee7c540e3bf19765695b1331c946ddf986d1516
C#-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

IntelliCode-Erweiterung   1.0
Detaillierte Informationen zur IntelliCode Visual Studio-Erweiterung

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++-Assistenten   1.0
Microsoft Visual C++-Assistenten

NuGet-Paket-Manager   5.7.0
NuGet-Paket-Manager in Visual Studio. Weitere Informationen zu NuGet finden Sie unter https://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

VC-Paket für Microsoft Visual Studio   1.0
VC-Paket für Microsoft Visual Studio

Visual Basic-Tools   3.7.0-6.20459.4+7ee7c540e3bf19765695b1331c946ddf986d1516
Visual Basic-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

Visual Studio-Tools für Unity   4.7.1.0
Visual Studio-Tools für Unity

Visual Studio Code-Debugadapter-Hostpaket   1.0
Interopebene zum Hosten der Visual Studio Code-Adapter in Visual Studio


2. Yes, I've checked this last comment. @MersGitHub updated to the newest version of the .NET Core SDK (3.0.100 in his case) and after that installed additionally .NET Core 2.2.402.

In my case the newest version is .NET Core SDK 3.1.402 and I installed additionally exactly the same older version, i.e. .NET Core 2.2.402.

The newest version is different, but the older version, which made things work for @MersGitHub, is exactly the same, see: 

![image](https://user-images.githubusercontent.com/72129017/94708575-0cf5e380-0345-11eb-8961-8338c8274f12.png)


3. No, I've not yet tried another version of VS. What version would you recommend?

**Comment by dmvtech** [comment] 2020-10-01 21:50
I'll take a look to see if I can reproduce this.

**Comment by dmvtech** [comment] 2020-10-06 00:28
Hi @MHeadroom Unfortunately I haven't been able to reproduce this yet. It should not be dealing with the tools or anything like that at this point (those are for a later point in the development/deployment process). If it's failing at just creating the project/solution, then it is something with the package, VS or the environment.

Can you verify the version of the visx template? For example, i'm using 4.9.1.2

![image](https://user-images.githubusercontent.com/43397658/95145265-a4857880-072f-11eb-942c-4de43ca14a2f.png)

The only other thing I can think of it is something to do with localization. I can try and see if I can reproduce when running with German instead of English.

**Comment by matiasroldan6** [comment] 2020-10-06 21:30
Hi @MHeadroom, we were unable to reproduce this issue so far.

We would like to join in on @dmvtech [request ](https://github.com/microsoft/botframework-solutions/issues/3671#issuecomment-703959702)and also ask for the VSIX version you are using.
Aside from that:

1. There's extra data you attached in the [VS Community report](https://developercommunity.visualstudio.com/content/problem/1194245/cannot-create-virtual-assistant-project.html) that we don't have access to. It would be very useful if you could **send us that data**. Also, send us if you have it the **`UpgradeLog.htm`** that should be in the project root according to the error message (the "migration report") .
2. Have you tried generating a Skill using the same marketplace extension? You had any errors?

We attempted to replicate your setting by having, among others:
- Microsoft Visual Studio Community 2019
```
 Version 16.7.5
 VisualStudio.16.Release/16.7.5+30523.141
 IntelliCode Extension   1.0
 NuGet Package Manager   5.7.0
 Visual Studio Tools for Unity   4.7.1.0
```

- Virtual Assistant and Skill templates marketplace extension. Since we weren't sure of what version you had, we tried the following:
  -  version [4.9.1.2 (latest)](https://marketplace.visualstudio.com/items?itemName=BotBuilder.VirtualAssistantTemplate&ssr=false#overview)
  -  version [4.8.0](https://botbuilder.myget.org/feed/aitemplates/package/vsix/VirtualAssistantTemplate.d2246051-7779-4196-af1f-ae7e2562ec8e/4.8.0.0)
  -  version [4.7.0](https://botbuilder.myget.org/feed/aitemplates/package/vsix/VirtualAssistantTemplate.d2246051-7779-4196-af1f-ae7e2562ec8e/4.7.0.0)

In all cases the `.sln` and the `.csproj` were generated correctly, with no error or migration messages.

We'll be attentive to any replies from you.

**Comment by MHeadroom** [comment] 2020-10-07 08:47
Hi @dmvtech and @matiasroldan6,

thanks for your help. I could create the Virtual Assistant now.

In answer to your questions: I had installed the visx template in version 4.9.1.2 and Visual Studio in version 16.7.5 all along from the first attempt.

But here's what I did:

1. I repaired my Visual Studio installation using the Visual Studio Installer. Creation failed.

2. As @dmvtech guessed that it could have something to do with the localization I added the English language package using the Visual Studio Installer. Creation failed.

3. I deinstalled and reinstalled Visual Studio using the Visual Studio Installer, this time only in the English Version. Creation succeeded.

Weird, but it looks like it has really something to do with the International Settings in Visual Studio.

Thanks again and let me now if you still need anything to reproduce this...

**Comment by matiasroldan6** [comment] 2020-10-07 19:38
Great to hear @MHeadroom that you managed to create the C# Virtual Assistant using [VSIX@4.9.1.2](https://marketplace.visualstudio.com/items?itemName=BotBuilder.VirtualAssistantTemplate&ssr=false#overview)!

If you agree, we can close this issue but feel free to raise an issue if you have a problem.

Last, but not least, we still couldn't replicate the issue following same environment that [you mentioned](https://github.com/microsoft/botframework-solutions/issues/3671#issuecomment-704789840) using the German language version.

Thanks again for reporting :blush:

**Closed as completed** 2020-10-10 00:10 UTC
Labels: Type: Bug, Support, Needs Triage, customer-reported, customer-replied-to, Bot Services
