### ISSUE TITLE
Virtual assistant dialogs need warmup

### ISSUE THREAD

**Issue by ipraveenMS** [microsoft/botframework-solutions#3748] opened 2021-01-04 23:12 UTC
#### What project is affected?
Latest VA sample and skills
#### What language is this in?
C#
#### What happens?
The VA invocation phrase "sample dialog" does not work from OnBeginDialogAsync. It goes to generic invocation instead of skill invocation. 
#### What are the steps to reproduce this issue?
1. Deploy sample VA 
2. Deploy sample skill
3. Connect skill to the VA
4. Deploy the bots to azure and register VA bot in teams
5. In Teams channel and start a new conversation; "Hi @SampleVA" and get a generic response from VA. Now "@SampleVA sample dialog" invokes sample skills. This is expected.
6. In Teams channel start a new conversation; "@SampleVA sample dialog". This invokes generic response instead of routing to skills
7. Reason for above is, in MainDialog.cs of sample VA, the new conversation is not handled correctly in InterruptDialogAsync (innerDc.ActiveDialog is null and other logic is not correct so it routes to generic response)

#### What were you expecting to happen?
Teams channel new conversation message "@SampleVA sample dialog" is routed to skills. Both step 5 and 6 should produce same response for "@SampleVA sample dialog" 
#### Can you share any logs, error output, etc.?
Above steps should give enough info.

**Comment by gabog** [comment] 2021-01-05 19:32
Hi @Batta32, can you review this one?

Thanks

**Comment by Batta32** [comment] 2021-01-05 20:31
Sure @gabog ! We will be reviewing this issue trying to reproduce the problem. As soon as we have any update we will back here 😊.

**Comment by Batta32** [comment] 2021-01-13 12:30
Hi @ipraveenMS, sorry for the delay. We are currently working on this issue, so this week we will let you know the updates 😊.

**Comment by VictorGrycuk** [comment] 2021-01-15 19:14
@ipraveenMS - We reproduced the issue and sending the skill utterance before or during the onboarding dialog will not activate the Skill. We checked why this is happening, and we believe this is **by design**.

The steps we took were the following:

1. Build and deploy the C# [Virtual Assistant sample](https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/assistants/virtual-assistant)
2. Build and deploy the C# [Skill sample](https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/skill)
3. Connect both using the [Botskills](https://github.com/microsoft/botframework-solutions/tree/master/tools/botskills) tool
4. Enable [Microsoft Teams channel](https://microsoft.github.io/botframework-solutions/clients-and-channels/tutorials/enable-teams/1-intro/)
5. Add the Virtual Assistant bot to Teams
6. Send `run sample dialog` as first message
7. The skill will not be triggered

Following the [Activity Handling](https://microsoft.github.io/botframework-solutions/virtual-assistant/handbook/activity-flow/) document:

1. When the first message is sent, the method [OnBeginDialogAsync](https://github.com/microsoft/botframework-solutions/blob/master/templates/csharp/VA/VA/Dialogs/MainDialog.cs#L86) is called.
2. Then it will call [InterruptDialogAsync](https://github.com/microsoft/botframework-solutions/blob/master/templates/csharp/VA/VA/Dialogs/MainDialog.cs#L201) to check if the conversation was interrupted
    1. It is OK for `dialog` to be null, as *no dialog has started yet*
    2. Also, since this method will return `false` because the current dialog is not a skill (so it won't ask the user if they wish to switch skill), and the utterance is not a General intent.
4. Since it was not interrupted, it will start with the first step of the [defined WaterfallStep](https://github.com/microsoft/botframework-solutions/blob/master/templates/csharp/VA/VA/Dialogs/MainDialog.cs#L60-L66), which is the [OnboardingStepAsync](https://github.com/microsoft/botframework-solutions/blob/master/templates/csharp/VA/VA/Dialogs/MainDialog.cs#L324) method.
5. It is not that until it reach the [RouteStepAsync ](https://github.com/microsoft/botframework-solutions/blob/master/templates/csharp/VA/VA/Dialogs/MainDialog.cs#L351)method step of the waterfall that it will [check if the intent is a skill utterance](https://github.com/microsoft/botframework-solutions/blob/master/templates/csharp/VA/VA/Dialogs/MainDialog.cs#L365-L376), and start the skill if it is.

**Comment by VictorGrycuk** [comment] 2021-01-15 19:15
@ipraveenMS - We found a **workaround**. It consists on extracting [the logic that checks](https://github.com/microsoft/botframework-solutions/blob/master/templates/csharp/VA/VA/Dialogs/MainDialog.cs#L361-L376) if the activity contains a skill utterance, and call it if it does, to its own method. Then that method can be called in earlier steps, such as before the OnBoardingStep or even in the InterruptDialog method.

This would require analyzing which should have a higher priority, if the onboarding process of the dialog, or the execution of the skill intent.

**Comment by ipraveenMS** [comment] 2021-01-19 19:57
@VictorGrycuk @gabog This is a regression from previous behavior. We have BF from the versions where this works (VA and skill are in the same process, not different micro services) . So its not by design, its a bug.

Regarding the workaround, yes this came to my mind. But my ask here for you to address this as a bug and actually fix it in the code base which is much preferable rather than doing some one off fixes to my code which creates issues every time I sync (when ever you release new BF version with VA code changes).

**Comment by VictorGrycuk** [comment] 2021-01-19 20:36
Hi @ipraveenMS, we will be re analysing this.
 We will let you know as soon as we have an update.

**Comment by ipraveenMS** [comment] 2021-01-19 22:14
Thats great, let us know when this is fixed. For now I have incorporated the workaround in my code.

**Comment by srinaath** [comment] 2021-01-29 19:08
@VictorGrycuk We are glad to hear the workaround fixed it. We currently do not have the staffing for the bug fix. Closing it for now.

**Closed as completed** 2021-01-29 19:10 UTC
Labels: Type: Bug, Team: Kobuk
