### ISSUE TITLE
Unable to properly end skill when user cancels out when skill is started from sub dialog in VA

### ISSUE THREAD

**Issue by tomSauret847** [microsoft/botframework-solutions#3437] opened 2020-06-01 18:59 UTC
#### What project is affected?
Virtual assistant
#### What language is this in?
TypeScript
#### What happens?
When you start a dialog, then start a skill from that dialog it does not get registered properly on the stack. When the user uses the "cancel" interrupt the skill never receives the end of conversation to reset.
#### What are the steps to reproduce this issue?
Create a VA and skill. start the skill from the "on boarding dialog of the VA. Try to cancel the skill using the interrupt and check if the skill receives the end of conversation
#### Can you share any logs, error output, etc.?
Dialog stack from skill started in a sub dialog
[ { id: 'MainDialog',
    state: { options: {}, values: [Object], stepIndex: 1 } },
  { id: 'TextPrompt', state: { options: [Object], state: {} } },
  { id: 'TransferDialog2',
    state: { dialogs: [Object] },
    version: '-43530585' } ]

dialog stack of skill started from main dialog
[ { id: 'MainDialog',
    state: { options: {}, values: [Object], stepIndex: 2 } },
  { id: 'dlpskill', state: {} } ]

**Comment by Batta32** [comment] 2020-06-01 19:27
Thanks @tomSauret847 for reporting this issue! As soon as we have any update we will back to you 😊.

**Comment by VictorGrycuk** [comment] 2020-06-08 18:32
Hi @tomSauret847! We were unsuccessful on trying to reproduce this issue.

We have some **questions** regarding your repro steps.
- Are you using the [generator-bot-virtualassistant@1.0.0](https://www.npmjs.com/package/generator-bot-virtualassistant/v/1.0.0)?
- Are you triggering the Skill by sending the utterance during the [onboardingDialog](https://github.com/microsoft/botframework-solutions/blob/master/templates/typescript/samples/sample-assistant/src/dialogs/onboardingDialog.ts) of the VA?
- Have you updated the VA in order to forward the intent to the Skill? If so, what modifications have you done to it?
- What do you mean with `TransferDialog2`? Is it a synonym to the `onboardingDialog`?

We noticed that there is a [validation](https://github.com/microsoft/botframework-solutions/blob/master/templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts#L218) in the `interruptDialog` method of the VA's MainDialog, that only switches to another Skill if the current dialog belongs to a Skill.
In the case of `onboardingDialog` this returns false, hence it not being interrupted to start the Skill sample.

This is our environment:
- [generator-bot-virtualassistant@1.0.0](https://www.npmjs.com/package/generator-bot-virtualassistant/v/1.0.0)
- TypeScript Virtual Assistant
- TypeScript Skill

We took the following steps to reproduce the issue:
1. Deploy Virtual Assistant and Skill
1. Connect the Virtual Assistant to the Skill
1. Run both bots in Bot Emulator
1. Send a Skill's utterance during the VA's `onboardingDialog`
1. The Skill was not initialized as the `onboardingDialog` was not finished

![image](https://user-images.githubusercontent.com/39467613/84066966-14137300-a99d-11ea-82e6-8b7060f1590b.png)

Thanks!

**Comment by tomSauret847** [comment] 2020-06-08 19:01
Currently we have our live agent transfer set as a skill to be able to escalate to a a live agent if the bot cannot resolve the customers issue (TransferDialog2). We need to perform some validation to ensure that the customer is transferred to the correct chat queue which is why we have built that into a dialog similar to the onboarding dialog. I call the agenttransfer skill with the following code in the transferDialog.

        const identifiedSkill: IEnhancedBotFrameworkSkill | undefined = this.skillsConfig.skills.get('agenttransfer');
        if (identifiedSkill !== undefined) {
            await this.activeSkillProperty.set(sc.context, identifiedSkill);
            return sc.beginDialog('agenttransfer', skillDialogArgs);

The VA will start the skill and forward all the customers messages to the skill, but if the customer triggers the "Cancel dialog" interrupt the VA will not send the end of conversation to the skill to allow us to clean up and end the skill. You did reproduce the steps but did not cancel the skill in your reproduction. That is where our issue is in being able to receive the EOC in the skill to clean up the used resources and close them out.

I am using a TypeScript VA
TypeScript Skill
I have updated both based on the changes that were posted to the "next" branch of the repo to ensure they are up to date
The skill is being triggered and functioning properly, it just does not receive the EOC when the customer chooses to cancel out of all the active dialogs.

**Comment by VictorGrycuk** [comment] 2020-06-08 19:18
Thanks @tomSauret847 for all the information 😊.
We will continue to reproduce the issue, and we will let you know of any update.

**Comment by VictorGrycuk** [comment] 2020-06-09 17:13
@tomSauret847, we want to **confirm** with you that we correctly understood the issue.

Based on what you said in your last comment we will work on recreating the following scenario:
1. Create a Virtual Assistant Sample
1. Create a Skill Sample
1. Modify the VA's `onboardingDialog` so it calls the Skill Sample. We will base our modifications on the shared snippet.
1. Send *cancel* once that the Skill Sample has started
1. Cancellation of the Skill Sample should fail

*This is how understood that your workflow is. You have a Virtual Assistant with a `TransferDialog2` dialog, which  initializes the AgentTransfer Skill*.
![image](https://user-images.githubusercontent.com/39467613/84178723-4683a580-aa5b-11ea-8b74-cc7cc7d9cfaa.png)

**Comment by tomSauret847** [comment] 2020-06-09 17:46
Thank you @VictorGrycuk That is the correct workflow of the scenario we are implementing. We can get the skill to work properly during the conversation, but when the customer cancels, the skill will not reset since it never receives the End Of Conversation.

**Comment by VictorGrycuk** [comment] 2020-06-12 16:48
@tomSauret847, after replicating your scenario we noticed that, cancelling the dialogs in the VA, the activity that carries the cancel utterance **does not reach** the Skill, therefore not raising the cancel event on the Skill side. Could you please **confirm** with us that this is the behavior that you are experimenting on your side?

This is our environment:
- [Branch](https://github.com/microsoft/botframework-solutions/tree/feature/southworks/cancel-activity-issue) with our modifications: 
- TypeScript Virtual Assistant
- TypeScript Skill

These were our repro steps to reproduce the above result with our branch:
1. Deploy both TypeScript samples
1. Connect Skill Sample to Virtual Assistant Sample
1. Add a breakpoint at the start of Skill Sample's [interruptDialog](https://github.com/microsoft/botframework-solutions/blob/feature/southworks/cancel-activity-issue/templates/typescript/samples/sample-skill/src/dialogs/mainDialog.ts#L143) and debug both samples
1. The [onboardingDialog](https://github.com/microsoft/botframework-solutions/blob/feature/southworks/cancel-activity-issue/templates/typescript/samples/sample-assistant/src/dialogs/onboardingDialog.ts) will start and trigger the [sampleDialog](https://github.com/microsoft/botframework-solutions/blob/feature/southworks/cancel-activity-issue/templates/typescript/samples/sample-skill/src/dialogs/sampleDialog.ts) name prompt
1. Send `cancel` instead of a name
1. Virtual Assistant sample will cancel both [mainDialog](https://github.com/microsoft/botframework-solutions/blob/feature/southworks/cancel-activity-issue/templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts) and [onboardingDialog](https://github.com/microsoft/botframework-solutions/blob/feature/southworks/cancel-activity-issue/templates/typescript/samples/sample-assistant/src/dialogs/onboardingDialog.ts), but the cancel activity will not reach the Skill's [interruptDialog](https://github.com/microsoft/botframework-solutions/blob/feature/southworks/cancel-activity-issue/templates/typescript/samples/sample-skill/src/dialogs/mainDialog.ts#L143) method.

Something to remark is that we got the same result by calling the skill's dialog either through the mainDialog instead of the onboardingDialog.

@darrenj
We did the same modifications on the C# samples and we got the **same behavior** as in TypeScript. 
Cancelling the dialogs in Virtual Assistant, either in OnboardingDialog or in MainDialog, the cancel activity does not reach the skill hence not raising the cancel event.

**Comment by tomSauret847** [comment] 2020-06-13 14:05
@VictorGrycuk Thank you for looking into this. Yes that is the issue we are experiencing on our deployment. One thing I did notice is when the skill is started from the onBordingDialog, the skill will be renamed to onBoardingDialog2 on the dialog stack. When it starts the skill it will just append "2" to the end of the dialog name that the skill is starting from. In my implementation if I start the skill from the mainDialog the skill will receive the cancel event and end the conversation in the skill. I only see this issue if I start the skill from a sub dialog and not the mainDialog.

**Comment by Batta32** [comment] 2020-06-16 15:06
Thanks @tomSauret847, we will continue reviewing this issue. As soon as we have any update, we will back to this thread 😊.

**Comment by VictorGrycuk** [comment] 2020-06-23 19:54
Hi @tomSauret847, sorry for the delay. We have additional questions as we want to understand better this issue and your implementation. We re analysed the issue, and we realized that we were focusing on the cancel activity instead of the EoC.

-   **Where and how are you checking if the EoC was received?** In your repro steps you mention *Check if the skill receives the end of conversation*
-   **Did you check the content of dialogContext registered dialogs?** In [your description](https://github.com/microsoft/botframework-solutions/issues/3437#issue-628655283) on the issue, you mentioned that the Skill is not being registered correctly on the stack, and in your [last comment](https://github.com/microsoft/botframework-solutions/issues/3437#issuecomment-643628330) you mention that it is being appended a `2`. Our supposition is that this happens because there is already a dialog registered with the same name.
-   **Is `dlpskill === agenttransfer`?** You showed two stacks, one of them is of the skill being started from the mainDialog.

We would appreciate any additional information that you can share with us about this as it might be related to this issue.

**Comment by tomSauret847** [comment] 2020-06-23 21:56
@VictorGrycuk Thank you for looking into this. 

**Where and how are you checking if the EoC was received?**
I am checking in the skill in the defaultactivityhandler in the onEndOfConversationActivity function. When started from the mainDialog this function will register the EoC

**Did you check the content of dialogContext registered dialogs?**
You were correct I had a dialog registered twice which I have fixed. The issue still remains that it will not send the EoC to the skill. Below is the stack log when it is connected to the skill
[ { id: 'MainDialog',
    state: { options: {}, values: [Object], stepIndex: 1 } },
  { id: 'TextPrompt', state: { options: [Object], state: {} } },
  { id: 'TransferDialog',
    state: { dialogs: [Object] },
    version: '-43530585' } ]
Here is a break down of the transfer dialog state while connected to the skill
{ dialogStack:
   [ { id: 'TransferDialog', state: [Object] },
     { id: 'agenttransfer', state: {} } ] }

**Is dlpskill === agenttransfer?**
No, the DLP skill is another skill we have attached that is always started from the mainDialog. I logged the output of it since it was already connected. The agent transfer is the only skill that will start from a sub dialog. This is to apply logic before escalating to a live agent.

Doing some more troubleshooting if you call cancelAllDialogs from the sub Dialog (transferDialog) the skill will receive the EoC. If it is only called from the mainDialog the skill will NOT receive the EoC. 
It appears the EoC is sent to the first dialog (transferDialog) but not the second dialog on the stack (agenttransfer).

**Comment by VictorGrycuk** [comment] 2020-06-24 20:09
@tomSauret847, we successfully reproduced your scenario. As next step, we will replicate the same changes and doing the same steps on the C#.

*Cancelling the Skill dialog after starting it from the mainDialog*
![image](https://user-images.githubusercontent.com/39467613/85622484-454a9f00-b63d-11ea-8757-d45428fe07c3.png)

*Debugger stopping at the onEndOfConversationActivity of the Skill. This does not happen if the Skill is started from the onboardingDialog*
![image](https://user-images.githubusercontent.com/39467613/85622467-3ebc2780-b63d-11ea-8669-c8c7194dccf1.png)

Environment

-   [Branch](https://github.com/microsoft/botframework-solutions/tree/feature/southworks/cancel-activity-issue) with our modifications:
-   TypeScript Virtual Assistant
-   TypeScript Skill

Repro Steps

1.  Deploy both samples
2.  Connect Skill Sample to Virtual Assistant Sample
3.  Add a breakpoint at the method `onEndOfConversationActivity` of Skill Sample's [defaultActivityHandler](https://github.com/microsoft/botframework-solutions/blob/master/templates/typescript/samples/sample-skill/src/bots/defaultActivityHandler.ts#L65) and debug both samples
4.  The [onboardingDialog](https://github.com/microsoft/botframework-solutions/blob/feature/southworks/cancel-activity-issue/templates/typescript/samples/sample-assistant/src/dialogs/onboardingDialog.ts) will start and trigger the [sampleDialog](https://github.com/microsoft/botframework-solutions/blob/feature/southworks/cancel-activity-issue/templates/typescript/samples/sample-skill/src/dialogs/sampleDialog.ts) name prompt
5.  Send `cancel` instead of a name
6.  The dialogs will be cancelled, but the debugger will not stop at the breakpoint

When we ran the same steps without the modifications, that is, starting the skill dialog from the MainDialog, the debugger **does** stop at the breakpoint.

**Comment by VictorGrycuk** [comment] 2020-06-26 20:55
@tomSauret847 - we have been looking into this issue and found that when `MainDialog` calls the `cancelAllDialogs` method, it will iterate through its active dialogs.

Then, when it starts to cancel the active dialogs of the `CustomDialog` that contains the skill dialog, it won’t cancel the skill dialog because it **won't find it** in the list of its dialogs.

We will continue working on this, we will back to you as soon as we have any update to you 😊.

### Debugging workflow:

1.  After sending the `cancel` utterance, MainDialog will call DialogContext's [cancelAllDialogs](https://github.com/microsoft/botframework-solutions/blob/master/templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts#L251) method
2.  After looking into `cancelAllDialogs` more closely, we see that the stack of MainDialog's active dialogs contains just `MainDialog` and `CustomDialog`. However, `sampleSkill` can be found inside of CustomDialog's dialogContext stack.
![image](https://user-images.githubusercontent.com/39467613/85900295-f7b56a00-b7d5-11ea-8ea1-96e8befaaeb2.png)
1.  It will start to cancel `CustomDialog` and eventually call its own DialogContext's [CancelAllDialogs](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/componentDialog.ts#L147) method.
2.  At this point we are back at step 2, except that from the point of view of the `CustomDialog`. It will start to cancel its active dialogs, which includes the `sampleSkill`.
3.  It will try to cancel the `sampleSkill`, but `this.findDialog('sampleSkill');` will return **undefined**, therefore failing to cancel the skill dialog.
4.  Taking a look into the `findDialog` method, we see that it is trying to find the `sampleSkill` inside of the dialog list. However, the sampleSkill can be found inside **stack** of dialog instances.
![image](https://user-images.githubusercontent.com/39467613/85900328-04d25900-b7d6-11ea-9419-3dae3f6c74bf.png)

**Comment by VictorGrycuk** [comment] 2020-07-02 18:05
@tomSauret847 we were able to raise the EoD event on the Skill side by registering the skill dialog in the sub dialog constructor.

**Implementation Steps**

1.  Add a `SkillDialog` array to the sub dialog's [constructor](https://github.com/microsoft/botframework-solutions/blob/feature/southworks/cancel-activity-issue/templates/typescript/samples/sample-assistant/src/dialogs/customDialog.ts#L39) parameters
    ```javascript
    public constructor(
        accessor: StatePropertyAccessor<IUserProfileState>,
        services: BotServices,
        templateManager: LocaleTemplateManager,
        skillDialogs: SkillDialog[],
        skillsConfig: SkillsConfiguration,
        activeSkillProperty: StatePropertyAccessor<BotFrameworkSkill>)
    ```
2.  [Register](https://github.com/microsoft/botframework-solutions/blob/feature/southworks/cancel-activity-issue/templates/typescript/samples/sample-assistant/src/dialogs/customDialog.ts#L60-L63) the Skill dialog inside the sub dialog's cosntructor.
    ```javascript
    // Register skill dialogs
    skillDialogs.forEach((skillDialog: SkillDialog): void => {
        this.addDialog(skillDialog);
    });
    ```
1.  On the [index](https://github.com/microsoft/botframework-solutions/blob/feature/southworks/cancel-activity-issue/templates/typescript/samples/sample-assistant/src/index.ts#L197), pass the skill dialog to the sub dialog's contructor.
    ```javascript
    const customDialog: CustomDialog = new CustomDialog(
        userProfileStateAccesor,
        botServices,
        localeTemplateManager,
        skillDialogs,
        skillsConfiguration,
        activeSkillProperty);
    ```
1.  After this, the skill dialog should be able to raise the EoC.

**Environment**

-   [Branch](https://github.com/microsoft/botframework-solutions/tree/feature/southworks/cancel-activity-issue) with our modifications:
-   TypeScript Virtual Assistant
-   TypeScript Skill

**Debugging workflow:**

1.  After observing that the skill dialog was not found when the dialogContext iterated through the sub dialog's list of dialogs, we found that these dialogs are registered in the sub dialog constructor
2.  We modified the sub dialog's constructor to [register the skill dialogs](https://github.com/microsoft/botframework-solutions/commit/74d3b5082aab515c28bca4a483d4accb2cfba849). We compared how the MainDialog registers the dialogs and found that the skill register used in the MainDialog was missing in the sub dialog
3.  After following the same steps we did in our [previous comment,](https://github.com/microsoft/botframework-solutions/issues/3437#issuecomment-650396840) we observed that the Skill dialog was on the list of the sub dialog's dialogs
![image](https://user-images.githubusercontent.com/39467613/86394613-3be0b880-bc75-11ea-8430-e1db08863e8d.png)
4.  Finally, since it was on the list, it can be found when the `dialogContext` search for it, and the event is raised on the Skill side
![image](https://user-images.githubusercontent.com/39467613/86394688-561a9680-bc75-11ea-823e-7dd35edc9dec.png)

We hope that this works for you and we will be attentive to your answer 😊.

**Comment by tomSauret847** [comment] 2020-07-02 19:31
Thank you @Batta32 !!! This has fixed the issue and we are able to get the skill to receive the EoC when the customer cancels the dialog.

**Comment by Batta32** [comment] 2020-07-02 19:34
Awesome @tomSauret847 - I'll close this issue! 🎉

**Closed as completed by Batta32** 2020-07-02 19:34 UTC
Labels: Type: Bug, Needs Triage
